### ISSUE TITLE
Docker Desktop - Paid support 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#104]
**Tell us about your request**
Provide the option to pay for support for Docker Desktop as part of a Docker Subscription 

**Which service(s) is this request for?**
Docker Desktop 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Today there is only a community support channel and public github repo for Docker Desktop. There is no model to get 'more' support as a paying user. 

**Are you currently working around the issue?**
Using public issues, waiting for responses and using community resources 

**Additional context**
Feedback on the price point would be useful from the community :)

**Comment by ingshtrom** [comment]
I would also be interested to hear what sort of SLA people think they should receive because that can greatly influence the cost and the burden on humans to be able to scale such a feature.

**Comment by StefanScherer** [comment]
There is better support for Pro and Team accounts now.
