### ISSUE TITLE
[Docker Desktop] Graphs of resources in desktop

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#11]
**Tell us about your request**
Display information about running container stats and information around desktop resource consumption on the machine as graphs within the UI

**Which service(s) is this request for?**
Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We get a lot of feedback about resource consumption in desktop and sometimes this is a rouge container or something else. We want to make this easier to diagnose and provide some useful tools for other analysis

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**

**Comment by amyb12345** [comment]
Hi! We added this extension(https://hub.docker.com/extensions/docker/resource-usage-extension) to help with the above issue. Please let us know if this is useful for you. We'd love your feedback!
