### ISSUE TITLE
Docker permissions

### ISSUE THREAD

**Issue by RobinGoussey** [docker/roadmap#111]
**Tell us about your request**
I would like to be able to have some sort of permissions system to limit what exactly a user can do in terms of docker (and compose). Right now, it is all or nothing. A user can start, stop, create containers as his heart desires. He could also exec into containers as he pleases, meaning he can read all secrets that are in some way in the container. So it might be nice to say user/group x, can start and stop containers, but can't build new ones, or pull new ones. This would make it able to run all containers as user x, where user x can only start stop containers, but can't pull or alter them. 

It would also be neat to put permissions on what folders a user can mount into his container. Because at the moment every docker user, can mount /etc, add himself to the sudoers, and boom, he has control over the whole system. 

So in general, it would be neat to have some kind of (fine-grained) permissions system, where
- The user/group is limited on what docker commands he can execute
- What folders he can volume/mount to the container. 
- The permissions also count for docker-compose

**Which service(s) is this request for?**
Docker engine (/compose)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm trying to find a way to limit the attack vectors of docker itself. If ever an attacker obtains an ssh key to a docker user, he can use docker to escalate his privileges, and root the machine. Or just have a distinction between system admins, and developers who need docker.

**Are you currently working around the issue?**
You could prevent certain docker commands by aliasing them in some way , but that doesn't prevent users from running a docker compose, and finding a way around it. Enabling DOCKER_CONTENT_TRUST=1 makes it extra effort for the attacker to pull images, but doesn't stop him from doing stuff on the entrypoint.

**Additional context**
If this by any means is out of scope, or there are better ways (have googled for a bit, haven't found much yet), or it is pointless, please let me know!

**Comment by nebuk89** [comment]
Hey @RobinGoussey thanks for the detailed request. Are you using Docker on Linux or Mac/Win? As some points here we could address in Mac/Windows more easily as admin features (we had some before in desktop enterprise)

**Comment by RobinGoussey** [comment]
Hi @nebuk89, we are using docker and docker-compose on linux at the moment.

**Comment by AkihiroSuda** [comment]
Have you tried rootless mode?

**Comment by RobinGoussey** [comment]
I've come across it, but haven't tried it yet. How does it limit users? Can users still mount for example etc folders if they are not sudo?

I'll have to experiment to see if my previous points are all mitigated by using rootless.

**Comment by RobinGoussey** [comment]
It appears, you can still mount those files, but there is nothing you can do to read/alter them in the container. So if the docker user has no access to a file, then neither will the container. 

Seems like running docker in rootless mode will fix the part where they can make themselves sudo. So while there are no fine-grained permissions on docker, they can be aliased away. Thank you very much!

**Comment by RobinGoussey** [comment]
@nebuk89 , are there any plans to make docker rootless mode non experimental? Also will there be an easy way to have multiuser support?

It took me a while, but I found how to have other users also use docker (in rootless mode), however it took me a while to figure out.

**Comment by AkihiroSuda** [comment]
Already non-experimental on git master (v20.0X).

**Comment by 3bars** [comment]
please add support for AWS Systems Manager Parameter Store. It provides the same function as Secret Manager for a lot less money. Sssshhhhh don't tell AWS ;)
