### ISSUE TITLE
Fine grained permission/scopes on personal access token

### ISSUE THREAD

**Issue by manishtomar** [docker/roadmap#115]
**Tell us about your request**
Add fine grained permission/scopes to personal access token to allow accessing non-registry APIs similar to how Github provides. This is an extension of [Official REST API](https://github.com/docker/roadmap/issues/20) feature and requires that to be supported first.

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I cannot automate many tasks in Hub. For example, after enabling 2FA If I am not using autobuilds I cannot update the repository's readme to VCS's readme.

**Are you currently working around the issue?**
Disabling 2FA and reverse engineering existing APIs from browser.

**Additional context**
https://github.com/docker/hub-feedback/issues/2006
https://github.com/docker/hub-feedback/issues/1927

**Comment by abitrolly** [comment]
I would be happy with just specific token for updating the image description. Just a single hardcoded function, without scope management.

**Comment by demyxco** [comment]
Hi guys, been following this for a while but is there any word on this?

**Comment by nebuk89** [comment]
@demyxco launch will be in the next 2 weeks 🎉  keep an eye on this ticket :D

**Comment by demyxco** [comment]
@nebuk89 so will there be documentations on how this work? Or just have 2FA enabled and use access tokens like normal?

**Comment by reconman** [comment]
There's this blog post about it, but it seems like it's only intended for paid users: https://www.docker.com/blog/level-up-security-with-scoped-access-tokens/

**Comment by modem7** [comment]
> There's this blog post about it, but it seems like it's only intended for paid users: https://www.docker.com/blog/level-up-security-with-scoped-access-tokens/

Even with read, write, delete it doesn't allow updating readmes unfortunately.

**Comment by eitsupi** [comment]
Any update?

**Comment by modem7** [comment]
> Any update?

Best comment on https://github.com/docker/hub-tool/issues/172 as this is for some reason closed. Even though it didn't resolve the original problem at all.

**Comment by christian-korneck** [comment]
same for me, I tried but [it didn't seem to work](https://github.com/docker/hub-feedback/issues/2127#issuecomment-1152831106). Not even with a paid Docker account. Does this work for anyone here? If so, I'd appreciate a pointer into the right direction.
