### ISSUE TITLE
Support ACI as a backend to Docker CLI using context 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#116]
**Tell us about your request**
Provide a way for users of the Docker CLI to deploy and work directly with containers in Azure Container instances through the Docker CLI. Make use of the Docker context command to move between working locally and interacting with ACI instances. 

**Which service(s) is this request for?**
Docker CLI 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Deploying to any cloud instances takes time to learn a new set of commands & functions, when most users simply want to 'run something as they did locally' either a single container or a group of containers using Compose 

**Are you currently working around the issue?**
Using unique commands or separate CLI tools to deploy to cloud instances 

**Additional context**
Experience overview https://docker.events.cube365.net/docker/dockercon/content/Videos/XBEpzDGMuM64ERg6Z

**Comment by jamiewest** [comment]
Will these also be supported in the remote engine api?

**Comment by justincormack** [comment]
@jamiewest the Azure integration work does not use the Docker remote API, as it talks to the Azure API directly. We are working on an SDK, initially as a prototype as well, but it cannot just be a remote Docker API endpoint.

**Comment by YANZ-ndroid** [comment]
4cd6824
