### ISSUE TITLE
Feature Request - Virtual Machine Driver

### ISSUE THREAD

**Issue by Neelerak** [docker/roadmap#118]
## Docker for Windows Feature Request
# I would like to see Virtual Machine Drivers brought into Docker for Windows like was included in Docker Toolbox, Reasons:
1. I have tried to switch my computer to use Hypher-V 3 times, each time it breaks my machine.  So bad, one time, I had to rebuild the entire OS.
2. I prefer the use of VirtualBox to Hyper-V, it is simpler and easier to use in my experience
3. Last point, I basically can not use Docker for Windows and have to keep using Docker Toolbox that I assume will fall behind at some point, please make my life easier.

**Comment by christophermclellan** [comment]
Thanks for submitting your issue and apologies for the delayed reply. This is not something Docker is considering working on and as such I'll close this.
