### ISSUE TITLE
why the repo of dockerhub is docker.io not hub.docker.com

### ISSUE THREAD

**Issue by zackzhangkai** [docker/roadmap#123]
why the repo of dockerhub is docker.io not hub.docker.com?

I know the official website is hub.docker.com, but in the fact ,  the repo is docker.io.  why?

e.g.
```
[root@node1 ~]# docker login -u xxx -p xxx docker.io
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

[root@node1 ~]# docker login -u xxx -p xxx hub.docker.com
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to https://hub.docker.com/v2/ failed with status: 404 Not Found
```

In another words, there is a scene:

First, when I google the dockerhub, then I got the hub.docker.io. And then, I can see all my repos.So now I may think the repo is this url.But , in the fact , it is not.So I got confused. Yes, I know the right one is docker.io.But to the primers, they may easily met with the same doubt. The main problem is that ,  I cannot find any docs about this message, that told me the registry address is `docker.io`.

**Comment by justincormack** [comment]
Hi, you don't need to specify the registry name for Docker Hub, so you don't generally need to know this. This is very historical, but difficult for us to change now.

**Comment by crazy-max** [comment]
See also https://docs.docker.com/registry/introduction/#understanding-image-naming

@justincormack About `registry-1.docker.io`, I think it's only available as an "edge" registry right?

**Comment by zackzhangkai** [comment]
Yes, in the general, I needn't to know specify it . But in some scenes, I do need, such as If I build some private repos and provide the offers to customers, then I should have to specify it explicitlly. To change the address is a difficult thing, but maybe that  offer some message to notify users is a good way.
