### ISSUE TITLE
Docker context support for ECS

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#124]
**Tell us about your request**
Support for Docker context CLI experience when working with AWS ECS services, allowing users to work with 'docker compose up' instead of the current 'docker ecs compose up'

**Which service(s) is this request for?**
ECS CLI Experience

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently the UX for the Docker ECS experience is divergent from the rest of the Docker CLI, it requires users to predicate all commands with an ECS noun. This makes is less consistent and makes it harder for users to re-use assets/tools to work with ECS

**Are you currently working around the issue?**
Using the 'docker ecs' commands that are available today

**Comment by RyanJarv** [comment]
+1 for moving this to the standard `docker compose up` scheme.

Thinking if this is done though we need to make sure it's clear exactly where a container is being created. Protect me from my stupidity please, is I guess what I'm saying. Recently ended up accidentally spinning up a fairly costly ECS cluster for a month or so before I realized I wasn't actually running my containers locally. RIP my wallet.
