### ISSUE TITLE
Consistent file event handling

### ISSUE THREAD

**Issue by daveisfera** [docker/roadmap#136]
**Tell us about your request**
File event handling stops working after a period of time when a host mount is used ( see https://github.com/docker/for-mac/issues/2417 )

**Which service(s) is this request for?**
Docker for Mac

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Above linked issue provides details and info

**Are you currently working around the issue?**
Yes, we have to restart Docker to get it to start working again

**Comment by stephen-turner** [comment]
This sounds like a bug report, not a feature request. Please file a new ticket on https://github.com/docker/for-mac instead, with repro steps and a new diagnostics ID. Thanks.

**Comment by stephen-turner** [comment]
(I know you put some details on the ticket you cited above, but that's a very old ticket and the original bug is probably not the bug you're now experiencing).

**Comment by daveisfera** [comment]
https://github.com/docker/for-mac/issues/4811

**Comment by stephen-turner** [comment]
👍 Thanks.
