### ISSUE TITLE
Why it doesn't work on windows 10

### ISSUE THREAD

**Issue by skchinna7** [docker/roadmap#140]
**Tell us about your request**
A clear and concise description of what you want to happen or the change you would like to see

**Which service(s) is this request for?**
Let us know which product(s) you want this for?

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

**Are you currently working around the issue?**
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Additional context**

It doesn't work on windows 10 what kind of software that doesn't work on windows 10

**Comment by nebuk89** [comment]
hey @skchinna7 , Docker supports running Docker on Windows 10 Pro, Enterprise and Home using WSL 2.
For enterprise users you can look at using Docker Enterprise engine on Windows server editions.

Closing ticket, reopen if I missed something.
