### ISSUE TITLE
Support Docker Desktop on nested virtualization(VDI)

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#141]
**Tell us about your request**
Support Docker Desktop running on nested virtualization/Virtual Desktop Infrastructure (VDI)  

**Which service(s) is this request for?**
Docker Desktop - Windows

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Today Docker Desktop is unsupported and doesn't work on VDI (as a rule), this means users of VDI cannot make use of Docker Desktop and have to use other solutions 

**Are you currently working around the issue?**
Fix forward or use another solution 

**Additional context**
Please provide feedback on the nested vert or VDI you would like to see Desktop on!

**Comment by Jonatan-V** [comment]
Strange that nobody has commented on this yet, but here goes. I would like to see support for windows 10 on citrix vdi :)

**Comment by dotnetneile** [comment]
+1 for support of VDIs. Seems strange it's not.

**Comment by knmscgcg** [comment]
Windows 10 on Azure/Hyper-V VDI support please.

**Comment by ylluminate** [comment]
This kind of nested virtualization on macOS on Apple Silicon would be amazing, but at this point it will require `qemu` virtualization due to the nested virtualization support being missing for the AS `arm64` implementation.

**Comment by christophermclellan** [comment]
Hi folks, for those that haven't seen our recent updates on VDI support, please see here for the latest - https://docs.docker.com/desktop/vm-vdi/

@Jonatan-V, I'd really like to understand more about your Citrix use case (sorry it's taken a while for someone to get back to you). Are you using Citrix Hypervisor ? If so, how are you enabling nested virt ?

Or are you using another Citrix product such as [Citrix Virtual Desktop and Apps](https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/whats-new.html) ?

**Comment by ylluminate** [comment]
@christophermclellan thanks so much for the update on this. Unfortunately it seems as though the page/article to which you linked us doesn't cover the macOS and Apple Silicon (m1, m2, etc.) topic... This, then, unfortunately doesn't really allow us to understand the landscape herewith clearly - which is still a very desperate situation.
