### ISSUE TITLE
[DockerHub] Clarification around the meaning of "image" in the FAQ on the image upcoming retention changes

### ISSUE THREAD

**Issue by hairyhenderson** [docker/roadmap#145]
**Tell us about your request**

_(sorry if this is the wrong place to ask for this, but it seemed to be the best way, even though this isn't technically a feature request!)_

It'd be great to get some further clarification on what exactly is meant by the term "image" in the Container Image Retention Policy FAQ at https://www.docker.com/pricing/retentionfaq.

Specifically:
1. do these changes apply to the image repository as a whole, or to tags/layers? (See https://twitter.com/sudo_bmitch/status/1293980220270280704 for a statement from @sudo-bmitch)
2. how is the Official Images program affected? See https://github.com/docker-library/official-images/issues/8552

Effectively what I'm asking for is the FAQ to be updated to eliminate the confusion 😉

**Which service(s) is this request for?**

DockerHub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Trying to understand the recently-announced retention changes, and how people will be affected.

**Are you currently working around the issue?**

n/a

**Additional context**

(see links above)

**Comment by manishtomar** [comment]
I believe latest FAQ should clarify any doubts. Please let us know if there needs more clarificationa.

**Comment by hairyhenderson** [comment]
Thanks @manishtomar - that clarifies everything I was looking for, and more! I'll close this now 🙂

**Comment by leonardehrenfried** [comment]
Has the deletion of inactive images for open source projects actually been implemented?

I can still see very old images that CI pushed to Dockerhub and I would be suprised if anyone has pulled them in the last 6 months. I would be totally fine if they were deleted.
