### ISSUE TITLE
[Docker Compose] Build Docker Compose in Go  

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#15]
**Tell us about your request**
Release a feature parity version of Docker Compose written in Go 

**Which service(s) is this request for?**
Dev-tools

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are generally aligned on Go for most of our development in Docker and Compose is an outlier for this. This also gives us an opportunity to revisit the UX of the CLI and make sure it is what people expect and need

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**

**Comment by dominikbraun** [comment]
When will the code of that new version be published, and is it going to be a branch of `docker/compose`? :)

**Comment by ndeloof** [comment]
@dominikbraun not sure how we plan to organize the code. We indeed could get it hosted on docker/compose as a "v2", which would help in the transition regarding feature requests/bug reports, but doing so would also isolate compose-in-go from the docker CLI, while we want compose to become a first-class citizen in the CLI.

**Comment by dominikbraun** [comment]
Thanks @ndeloof, I just asked because I don't want to miss the publication of the project since I'd really like to contribute.

**Comment by nebuk89** [comment]
@dominikbraun or others who have up voted this, would any of you be interested in running through what you are looking to do with Compose in Go? If so drop me an email on bengotch@docker.com. Thanks!

**Comment by ShadowJonathan** [comment]
Will this deprecate the python version of docker-compose?

**Comment by JohnPreston** [comment]
> Will this deprecate the python version of docker-compose?

Same concern as @ShadowJonathan, hope this does not mean the py package won't see any updates anymore...

**Comment by SebDanielsson** [comment]
When could this be done? A version written in go would be great for us portainer as referenced above!😃

**Comment by ndeloof** [comment]
@SebDanielsson see https://github.com/docker/compose-cli/tree/main/local/compose
Already deployed as `docker compose` by latest Docker Desktop for Mac/Windows users

**Comment by SebDanielsson** [comment]
Is Apple Silicon support planned fornthe next major release? Is it planned for february or mars? Ready to get the Macbook Air when Docker is supported👍

**Comment by anshrma** [comment]
@ndeloof / @nebuk89 - What would be the `docker-compose build` and `docker-compose push` equivalent in docker compose ?

**Comment by ndeloof** [comment]
@anshrma Both are supported already, did you have it a try?

**Comment by chris-crone** [comment]
So now that `docker compose` has been in Docker Desktop for a while, have any of you tried it? Any feedback?

> Will this deprecate the python version of docker-compose?

@ShadowJonathan @JohnPreston We don't have plans to change anything on `docker-compose` yet. We need more feedback on `docker compose` before we know what we'll do with it. What are you using the Python packages for?

> Is Apple Silicon support planned fornthe next major release? Is it planned for february or mars? Ready to get the Macbook Air when Docker is supported👍

@SebDanielsson We have a preview of Docker Desktop for M1 which you can find here: https://docs.docker.com/docker-for-mac/apple-m1/

**Comment by ProgrammerPepe** [comment]
Has anyone else noticed that `docker compose` builds faster than `docker-compose`? (I assume it's due to being written in go)

**Comment by ndeloof** [comment]
@ProgrammerPepe both `docker-compose build` and `docker compose build` do rely on the engine to execute the required build commands, so the command line being written in go has no impact. But `docker compose` uses Buildkit by default (while this is an option for `docker-compose`, and Buildkit uses advanced cache and parallelism optimizations to make builds faster.

**Comment by abdennour** [comment]
Who can list all difference points between docker compose and docker-compose ?

**Comment by ndeloof** [comment]
@abdennour `docker compose` has been designed to be backward compatible with `docker-compose`
if introduces a few new commands (`compose ls`, `compose cp`) and allow to run commands without the original compose.yaml file (by passing `-p <project_name>` flag)
But the main point is that "Compose v2" will evolve aside the Docker CLI, with ability to share code, so won't be 6 to 12 months late to adopt new features.

**Comment by JohnPreston** [comment]
@ndeloof can we guarantee that whichever compose we use, `docker compose` or `docker-compose`, the compose-specification will remain the source of truth for both tools when it comes down to the definition of it, and that for shell related integrations, ie env vars and such substitutions will remain the same in both so that, which ever tool one uses, they do not have to make changes do the source compose files?
Not doing so would most certainly ruin the whole experience that devs love by using compose.

**Comment by ndeloof** [comment]
@JohnPreston I can't "guarantee" anything :) but the intent is to offer a smooth migration from `docker-compose` to `docker compose`, which means the existing behaviors _should_ be replicated. While there might be a few "features" we might want to revisit, we don't want to create friction.

**Comment by JohnPreston** [comment]
I understand that you might want to have new features, but the specification for compose *must* be respected in either projects with the same source schema, otherwise you might as well not use either.

One thing that I find odd when you say the intent is to migrate to `docker compose` in GO away from the python version, is that, I assume, I then need a fully installed docker environment. I can think of many cases where I would like to be able to use docker-compose for validation and other standalone tasks which do not require to have docker installed to start with, and all one needs is python which is widely installed by default.

**Comment by ndeloof** [comment]
`docker compose` installation obviously is distinct from the `docker-compose` one, there will be some migration effort. But afaict there are a very few set of users to install `docker-compose` but not `docker` on a system. The only command you can run without a docker engine is `config`, which isn't very useful: Using docker-compose to "validate" is not highly relevant: it doesn't mean your compose file will start successfully, just it matches the schema bundled in your tool. `docker compose config` can be used for the same purpose if you're looking into this feature.

**Comment by JohnPreston** [comment]
> `docker compose` installation obviously is distinct from the `docker-compose` one, there will be some migration effort. But afaict there are a very few set of users to install `docker-compose` but not `docker` on a system. The only command you can run without a docker engine is `config`, which isn't very useful: Using docker-compose to "validate" is not highly relevant: it doesn't mean your compose file will start successfully, just it matches the schema bundled in your tool. `docker compose config` can be used for the same purpose if you're looking into this feature.

Fair enough.
