### ISSUE TITLE
[Docker Hub] Inactive Image Retention Policy

### ISSUE THREAD

**Issue by pkennedyr** [docker/roadmap#152]
**Tell us about your request**
In order to sustainably scale the free services Docker offers to our growing community of users, we are making an update to our terms of service regarding retention of inactive images. Inactive images are defined as images that have not been pulled or pushed in 6 months. 

Starting November 1, 2020:

- Free accounts may retain inactive images for up to 6 months
- Pro and Team subscriptions may retain inactive images indefinitely

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
To help Docker economically scale its infrastructure to support free services for our growing base of users, a new inactive image retention policy was introduced that will automatically delete images hosted in free accounts that have not been used in 6 months.

**Are you currently working around the issue?**
N/A

**Additional context**
For additional details, please see the [FAQ](https://www.docker.com/pricing/resource-consumption-updates) and our recent blog post regarding the [inactive image retention policy](https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/).

If you have a free account, you may upgrade to a Pro or Team subscription [here](https://www.docker.com/pricing).

The updated Docker Terms of Service are available [here](https://www.docker.com/legal/docker-terms-service).

**Comment by hopeseekr** [comment]
Is there any update on this? Did Docker silently abandon this line of action? Did they silently implement it sometime in the past? If so, when?
