### ISSUE TITLE
Delta updates for Docker Desktop 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#153]
**Tell us about your request**
Improve the update experience of Docker Desktop for Mac & Windows by moving to delta updates. This means that rather than having to download and install a 'whole new version of Docker Desktop', we would instead just install the delta and restart Docker Desktop. This should reduce the download size to 10-30mb (compared to ~400mb) and result in update times taking ~seconds rather than minutes. This will also allow us to move to background downloads of updates and be ready to 'just restart' as the user experience.

**Which service(s) is this request for?**
Docker Desktop for Mac/Windows 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Today Docker Desktop updates are infrequent on Community as we are aware that the process of updating is slow, interrupts user flow and requires a large download.  This also results in fragmentation of our user base where people are not getting the latest features quickly. 

**Are you currently working around the issue?**
Only releasing occasionally to community desktop 

**Additional context**
N/A

**Comment by minusdavid** [comment]
Docker Desktop version 3.0.0 claims to use delta updates. Can you speak more to how this is done or point to a commit?

**Comment by bam80** [comment]
Why this is closed?

**Comment by adityazeta** [comment]
Currently on v4.15.0, it is still needs to download ~500MB file.
Is the update cycle work in-progress?
