### ISSUE TITLE
Enhance the docker windows installer to have an option NOT to install the daemon (and Hyper-V)

### ISSUE THREAD

**Issue by ProfDrYoMan** [docker/roadmap#155]
**Tell us about your request**
There should be an option to NOT install the docker daemon (and Hyper-V) if only the CLI tools are needed (and allowed).

**Which service(s) is this request for?**
Docker Windows Installer.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It is not allowed to install docker (Hyper-V / WSL) in some companies.

**Are you currently working around the issue?**
No workaround available.

**Additional context**
See https://github.com/docker/for-win/issues/8872

**Comment by justincormack** [comment]
This is the same as #144?

**Comment by ProfDrYoMan** [comment]
Yes. Seems to be the same. I envision an installer which installs the same as now, but NOT the daemon.

- docker-cli
- compose-cli
- ... everything but the daemon

**Comment by stephen-turner** [comment]
I think we can dupe this against #144.
