### ISSUE TITLE
Docker Hub CLI

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#158]
**Tell us about your request**
Provide access to Docker Hub information such as images, teams and information on when images will expire from the local CLI 

**Which service(s) is this request for?**
CLI/Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently there is no easy way to use scripts or have a local experience to inspect my Hub content 

**Are you currently working around the issue?**
Using Hub UI 

**Additional context**
Should provide information related to image retention

**Comment by olegburov** [comment]
Duplicates https://github.com/docker/roadmap/issues/117

**Comment by nebuk89** [comment]
@olegburov d'oh 🤦
