### ISSUE TITLE
@mjsax

### ISSUE THREAD

**Issue by ajrh1984** [docker/roadmap#168]
@mjsax 
Is there a possibility that the task will be reflected?
We'll follow up if possible.

__Originally posted by @highluck in https://github.com/apache/kafka/pull/8022#issuecomment-647141512__

**Comment by ingshtrom** [comment]
I'm not sure what the question is here? Could you please follow the template for creating issues under the Docker Roadmap? Thank you!

**Comment by stephen-turner** [comment]
I think this is a typo. I'm going to close it: it can be reopened later if necessary.
