### ISSUE TITLE
Support being able to set CPU/memory limits from the CLI (Docker Desktop)

### ISSUE THREAD

**Issue by myitcv** [docker/roadmap#170]
Per @nebuk89 [on Slack](https://dockercommunity.slack.com/archives/C2TJ8FEJY/p1601917300015000?thread_ts=1601717266.014000&cid=C2TJ8FEJY), raising this as a follow up to https://github.com/docker/for-mac/issues/4907

**Tell us about your request**

I would like to be able to configure the CPU and memory limits from the CLI (context here is Docker Desktop for Mac)

**Which service(s) is this request for?**

Docker Desktop (for Mac)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

When using Docker Desktop for Mac via a CI setup (i.e. headless) environment, it is impossible to set CPU/memory limits. 

**Are you currently working around the issue?**

No, there does not appear to be a workaround as of today.

**Additional context**

n/a

**Comment by stephen-turner** [comment]
BTW there is a workaround to edit the settings.json file directly. (This doesn't take away from the feature request to be able to do it on the CLI).

**Comment by myitcv** [comment]
Thanks @stephen-turner - is there a reference/example of this file somewhere I could use?

**Comment by stephen-turner** [comment]
No, it's not documented, but the format is pretty obvious.

**Comment by myitcv** [comment]
Thanks is there an example file I can look at somewhere?

**Comment by stephen-turner** [comment]
You have one on your machine already, so it's just a matter of editing the existing one. Sorry, I don't remember the exact path at the moment as I'm on a Windows machine, but I think you can find it: if not, ask again.

**Comment by myitcv** [comment]
I don't actually have Docker installed myself, I'm iterating via GitHub Actions.

But I found the answer:

https://github.com/tmc/d4mctl/blob/91364c404614ebc87d036212bcc5c1974ace6a87/d4m/config.go#L11

Thanks again!

**Comment by stephen-turner** [comment]
Great, thanks.

Your request is actually a specific instance of a class of feature requests we get, so I've made a roadmap item for the general case, #172. I'll close this ticket in favour of that one, but please do vote on that one with a 👍.
