### ISSUE TITLE
Image Vulnerability Scanning in the Docker CLI (w/Snyk!) FOR LINUX

### ISSUE THREAD

**Issue by esemate** [docker/roadmap#171]
Please make the Image Vulnerabilty Scanning in the Docker CLI available in LINUX 

Gracias!

**Comment by nebuk89** [comment]
Thanks for opening @esemate ! We are working out how we would bundle all the bits 👀

**Comment by Tandolf** [comment]
any update on this? majority of the worlds build servers want to be able to scan the image in the build process...

**Comment by psanchezc23** [comment]
I'm also interested in that! I'll keep an eye on this issue! Thanks!

**Comment by nebuk89** [comment]
Shipped! https://github.com/docker/scan-cli-plugin/releases/tag/v0.8.0 and should be in releases from 20.10.6 and up
