### ISSUE TITLE
Docker Dashboard UI issue - image name foreshortened

### ISSUE THREAD

**Issue by psychemedia** [docker/roadmap#174]
The Docker Dashboard provides a tabular display of images, tag, image ID, creation data and size.

The columns are of equal width and fixed width.

For images with long names, particularly of the form `VERY_LONG_ORGANISATION_NAME/IMAGE`, this can make it hard to identify which image is which.

On a Mac:

![image](https://user-images.githubusercontent.com/82988/99668217-59b48b80-2a65-11eb-8a0e-4e2894b4b901.png)

It would be useful to be able to:

- resize / drag the columns, or
- give the image name a larger column width, or
- provide a tooltip to display the full image name when the mouse hovers over it

**Comment by nebuk89** [comment]
@psychemedia thanks for raising, we had added this as a bug in our backlog. We will probably start with a tooltip at least on hover over here and in the details view
