### ISSUE TITLE
Expose daemon on tcp://localhost:2375

### ISSUE THREAD

**Issue by MPV** [docker/roadmap#189]
### Expected behavior

Being able to expose Docker on `TCP` port `2375`.

Nowadays [you can do this with Docker Desktop for Windows](https://stackoverflow.com/questions/60151451/how-to-expose-2375-from-docker-desktop-for-windows): 

![vCH5O](https://user-images.githubusercontent.com/62675/105493120-3ef6d100-5cb9-11eb-9dda-4d7ba33e6b40.png)

### Actual behavior

No option for doing this in the Docker Preferences:

<img width="1362" alt="Skärmavbild 2021-01-22 kl  13 54 33" src="https://user-images.githubusercontent.com/62675/105493217-62ba1700-5cb9-11eb-80c8-ff43efb530b8.png">

Also, the Docker Preferences crashes if you try to set a configuration that tries to enable this (in Preferences > Docker Engine):

```json
{
    "debug": true,
	"hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"],
    "experimental": false
}
```

There are previous issues discussing this, for example:
- https://github.com/docker/for-mac/issues/770
- https://github.com/docker/for-mac/issues/1156
- https://github.com/docker/for-mac/issues/1765

...and [workarounds using `socat`](https://github.com/docker/for-mac/issues?q=socat)...

...and [security considerations](https://security.stackexchange.com/questions/205815/what-are-the-risks-of-exposing-the-docker-for-windows-daemon-on-localhost)...

*...but I hope we could revisit this now that it's a proper feature in Docker Desktop for Windows?* ❤️

**Comment by justincormack** [comment]
You don't mention your use case, why do you want this? I think the reason it is available in Windows is that Unix socket or named pipe support has historically been weak so there is more use there. However, the security problem is major, as it will expose root access to the Docker VM to your browser, for example, which is very dangerous.

**Comment by stephen-turner** [comment]
We have actually talked about removing it from Windows for this reason.

**Comment by christophermclellan** [comment]
Thanks for submitting your issue. This is not something Docker is considering working on and as such I'll close this issue.
