### ISSUE TITLE
Check for Administrator Rights before attempting update

### ISSUE THREAD

**Issue by jonesiscoding** [docker/roadmap#190]
**Tell us about your request**

Before downloading and prompting for the installation of, or attempting the installation of an update to Docker Desktop for Mac, the software should verify that the current user is an _Administrator_ on the machine as these rights are required for installation.

**Which service(s) is this request for?**

Docker Desktop for Mac

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

If the user is not an administrator, they will be unable to complete the installation of any update, so the download is an unnecessary use of bandwidth.  

The prompt and/or attempted installation can cause confusion to the user, making them think they cannot continue to use Docker Desktop until an administrative user intervenes.

**Are you currently working around the issue?**

Currently, I am advising users without access to an Administrator account to stay on Docker Desktop v2.5.1, which avoids the issue but has the side effect of causing additional version fragmentation, which I understand that the auto-update feature was added to prevent.

**Additional context**

This request stems from the discussion in docker/roadmap#183, as one part of a potential resolution for the issues discussed there.

**Comment by gsxryan** [comment]
This is required on Docker Desktop for Windows users as well.

**Comment by stephen-turner** [comment]
Let's roll this discussion into #183 rather than fragmenting different aspects of it.
