### ISSUE TITLE
Allow Automatic Deferral of Updates

### ISSUE THREAD

**Issue by jonesiscoding** [docker/roadmap#191]
**Tell us about your request**

Add a preference that allows for the automatic deferral of updates for X days, limited to a period of time that may be considered reasonable by both the developers and users of Docker Desktop.  This preference could default to 0 days, which would mirror the present behavior in Docker Desktop for Mac 3.x

**Which service(s) is this request for?**

Docker Desktop for Mac

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

At times during the normal usage of Docker Desktop, the software may need to be restarted.  In fact, this is likely why there is a restart option on the menu and in the preference, rather than forcing the user to quit and reopen the software in those cases.  

When there is a pending update for Docker Desktop, restarting the software will attempt the installation of that update, which may force the user to stop their present task to handle any post-installation tasks, such as the update of compose configurations, 3rd party tools, environments, etc.  It should be noted that _some users may not have the technical skills or knowledge needed to make those changes_.

In the event that the update to Docker Desktop introduces, deprecates, or unintentionally breaks a feature; other actions, troubleshooting, or adjustments to workflows may be immediately needed further disrupting the user's intended tasks.  As with above, _some users may not have the technical skills or knowledge needed to make those immediate changes_.

The potential for lost productivity is large; other users have cited direct examples of this in various threads discussing the auto-update feature.  While it is understood that updates are needed and that required updates can greatly decrease the amount of time it takes to support the software by reducing version fragmentation, allowing a user no control over when those required updates install removes their ability to plan updates for a time that works with their schedule.  Additionally, this may force an update at a time when their support staff and/or senior team members may be unavailable to assist them.

**Are you currently working around the issue?**

Currently, I am advising users with concerns to continue using version 2.5.1, which does not contain the automatic update feature.  Unfortunately, this may lead to additional version fragmentation, which I understand to be the reason the automatic update feature was added.

**Additional context**

Additional relevant discussion can be found in #183.

**Comment by jonesiscoding** [comment]
@sstock added another relevant point about allowing for users to choose when to download and install updates in [this comment](https://github.com/docker/roadmap/issues/183#issuecomment-778259153) of #183.  _Not all users are using an unmetered internet connection._  

Downloading the update in advance to allow for a quick installation when the user restarts the software may be using expensive or limited data.  It may be possible on Windows to determine if a connection is metered through the API, however no such (native) facility exists on macOS.

**Comment by stephen-turner** [comment]
I think this is pretty much covered in the discussion on #183, or if there are any further points they can be added there. I'm going to close this ticket to avoid fragmenting the discussion.

**Comment by philippe-granet** [comment]
See https://github.com/RektInator/kill-docker-auto-update
