### ISSUE TITLE
Shell/Terminal History Needed

### ISSUE THREAD

**Issue by sosensible** [docker/roadmap#203]
**When we shell out or rather into a container, the terminal would be SOOOooo.... much nicer if we could have history vs having to retype commands in full detail.

**My use currently is on Docker Desktop for windows, but who would not want this?

**Challenge or Frustration: When working on updates or new projects. We may try things over and over but have to type the whole command in vs using history and doing mods.

**Comment by gmsantos** [comment]
In theory, you can create a file map to persist the history outside the container and share it between your containers. Not sure if should be handled from the docker side.

**Comment by sosensible** [comment]
I just want history during the same shell session.

**Comment by christophermclellan** [comment]
Thanks for submitting your issue. This is not something Docker is considering working on for the time being, and as such I'll close this issue.
