### ISSUE TITLE
[Docker Hub] Identity & access management with SAML single sign-on

### ISSUE THREAD

**Issue by pkennedyr** [docker/roadmap#21]
**Tell us about your request**
Identity & access management with SAML single sign-on

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Configure SAML single sign-on (SSO) within a Docker Hub account as a way to control and secure access to organization resources on Docker Hub.

**Are you currently working around this issue?**
N/A

**Additional context**
N/A

**Attachments**
N/A

**Comment by ingshtrom** [comment]
Do we have an idea of initial supported SSO providers? *cough* Okta *cough* :smile:

**Comment by olegburov** [comment]
I would vote for https://auth0.com/

**Comment by justincormack** [comment]
What providers would people like?

**Comment by kencochrane** [comment]
Okta please

**Comment by sirlatrom** [comment]
Auth0 please

**Comment by tyrken** [comment]
Google

**Comment by davejgardner** [comment]
Azure AD

**Comment by luketainton** [comment]
Keycloak please! OpenID Connect support would also be appreciated 😄

**Comment by taiidani** [comment]
OneLogin and/or OpenID Connect as well

**Comment by ilyastoli** [comment]
JumpCloud

**Comment by MattSnow-xlnx** [comment]
SAML (Okta)

**Comment by trouserless** [comment]
OIDC would be great, SAML works too.

**Comment by HarlemSquirrel** [comment]
SimpleSAMLphp

**Comment by kyung-s-deepr** [comment]
AWS Single Sign-On

**Comment by ollio** [comment]
OpenID Connect support please, will integrate with all providers

**Comment by richardcardona** [comment]
Ping Identity

**Comment by rogerfernandes** [comment]
We really need this!
My company will move to Harbor or AWS ECR because one of the main problems with DockerHub is access control.

**Comment by tldusdev** [comment]
Azure AD Support would be nice.

**Comment by innocuoussoul** [comment]
is there a timeline for this?

**Comment by DavidFrahmVS** [comment]
Also interested in the timeline for this, and definitely would prefer it on any level of paid account.

**Comment by seanism** [comment]
bump.  This is a requirement for a lot of security and IT teams.

**Comment by voliveirajr** [comment]
Active Directory

**Comment by strikesec** [comment]
Looks like it's coming soon... and... we have to pay extra to be secure instead of it being baked into the product  as a core feature without any upgrades. Awesome.

**Comment by strikesec** [comment]
> is there a timeline for this? Also, please don't contribute to SSO tax by making this an enterprise level feature. SSO should be standard for businesses of all sizes.

![image](https://user-images.githubusercontent.com/92828486/140371694-50b62494-920f-4c5c-8579-679707089ed1.png)

**Comment by khalidosmani-lw** [comment]
Okta SAML SSO.

**Comment by majormoses** [comment]
> is there a timeline for this? Also, please don't contribute to SSO tax by making this an enterprise level feature. SSO should be standard for businesses of all sizes.

@innocuoussoul in the meantime: https://github.com/robchahin/sso-wall-of-shame/pull/262

**Comment by innocuoussoul** [comment]
Can’t say I didn’t see that one coming…

**Comment by izzychu** [comment]
We released SSO today! [https://dockr.ly/3A2UEdZ](url) Thank you for sharing your thoughts and patience.

**Comment by jamesmbourne** [comment]
Link above is broken, should take you to https://dockr.ly/3A2UEdZ ☝️

**Comment by izzychu** [comment]
> @izzychu the link above is broken, should take you to https://dockr.ly/3A2UEdZ ☝️

Thank you!!
