### ISSUE TITLE
Docker Volumes GUI 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#215]
**Tell us about your request**
Provide a GUI on the Desktop for users to view & manage their volumes. Including the ability to:
- View the contents of volumes 
- Add/remove files from my local host 
- View the history of a volume (what created it/what containers have interacted with it)
- See which volumes are currently in use 
- Prune/remove unused volumes 

**Which service(s) is this request for?**
Docker Desktop 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Working with volumes today can be tricky, it is hard to clear up old volumes as you cannot be sure without strong naming which volumes have been used by which containers. There is no simple way to 'dig into' a volume to do this either 

Getting contents in/out of a volume is not 'one click simple' and there is no need for it not to be 

**Are you currently working around the issue?**
Using some of the Docker CLI and otherwise having to use other tools/start new containers to look into volumes to work this out

**Additional context**
![volume1](https://user-images.githubusercontent.com/2938470/116541484-6de99800-a8e3-11eb-9aba-d645f8fd993a.PNG)
![volumes2](https://user-images.githubusercontent.com/2938470/116541488-6e822e80-a8e3-11eb-9eee-82d3285c45c6.PNG)

**Comment by hkt107** [comment]
https://github.com/hkt107/PowerShell.git

**Comment by multinerd** [comment]
Is this really going to be restricted to pro and above?
We're using docker on a machine with no internet access (local only)

![image](https://user-images.githubusercontent.com/6367998/122090919-489ee380-cdd6-11eb-8406-0c87e06d6b02.png)

**Comment by aleon1220** [comment]
UI for Linux distros?

**Comment by vikasdhiman0635** [comment]
can I access docker volumes in free plan?

**Comment by child-duckling** [comment]
why is this behind a paywall?

**Comment by NikitaKozlovtcev** [comment]
I have Pro plan but this functional is still not available
![image](https://user-images.githubusercontent.com/72300582/131317347-716bc250-c33f-4ae5-8338-ca6e7c68506a.png)
![image](https://user-images.githubusercontent.com/72300582/131317565-a04b5a8a-ab8e-4e15-9bca-5e469d23feef.png)

**Comment by nebuk89** [comment]
@NikitaKozlovtcev can you drop me an email on bengotch@docker.com... you should have access as a Pro user :(

**Comment by nebuk89** [comment]
Closing as shipped :)

**Comment by NikitaKozlovtcev** [comment]
> @NikitaKozlovtcev can you drop me an email on [bengotch@docker.com](mailto:bengotch@docker.com)... you should have access as a Pro user :(

At the moment everything is working well, after purchasing the PRO plan it just took 2 days to wait.

**Comment by carehart** [comment]
`Does this feature (in Pro and above) really provide a UI to let us explore the files/folders inside a volume? 

That was one of the points in the original post here, but the pop up we get refers only to how it can "_Simplify local volume management with a full view into the size of the volume and large files._"   And [the pricing page](https://www.docker.com/pricing) also indicates only that the paid version can "explore" volumes, without explaining what that really means.

**Comment by maxzhuo** [comment]
Only Save As or Remove, how to upload files?
