### ISSUE TITLE
Forcing updates breaks development environments

### ISSUE THREAD

**Issue by choeyio** [docker/roadmap#216]
The latest version of Docker on Mac has a breaking bug.  Our development has completely halted due to this bug.  Whenever we downgrade to a previous version of Docker, the issue is resolved, until Docker forces the latest version on us and our development environment breaks again!

It's absolutely baffling to me that this is considered acceptable!  The software is unusable! We are unable to work and are bleeding time and money all because you have chosen to remove what should be a standard feature to prevent situations like this from happening.

Due to the amount of attention this particular issue is receiving, it's pretty clear this decision has caused a lot of people a lot of pain.

**Comment by nebuk89** [comment]
Hey
To encourage developers to stay up to date, two weeks after an update becomes available, a daily reminder will appear, which you can dismiss.

If you use Docker Desktop at work you may need to skip a specific update. For this reason, Pro or Team subscription developers can skip notifications for a particular update when a reminder appears.

 **Free users will not be required to install any particular update, but they will continue to get reminders to update.**

https://www.docker.com/blog/changing-how-updates-work-with-docker-desktop-3-3/

**Comment by invictus80** [comment]
First and foremost the issue I seem to be having is the build it self and it causing issues for others to work around and no this not a prank My intentions are not to have developers (team members)work night and day. It's an issue of developers (actors) that really didn't care or understood what it takes to create and did not want to adhere tomy personal privacy and released prototypes before fully completed
