### ISSUE TITLE
"OS X 10.13 is not supported" popup spam

### ISSUE THREAD

**Issue by bbkr** [docker/roadmap#220]
Hi

I am using macOS 10.13 with no intentions of ever upgrading (due to 32-bit support dropped in newer versions). Unfortunately Docker 3.0.3 started spamming me on regular basis with following popups:

```
OS X 10.13 is not supported

There is an update but you are on OS X 10.13 or an earlier version.
Upgrade to the latest version of macOS to install it.
```
(always two of them at a time)

**Can you please advice how to disable autoupdate check?**

- yes, I am aware autoupdate cannot be disabled in options
- yes, I am looking for **any** hack that will get the job done (DNS block, damaging autoupdate files, etc).
- yes, I'm OK with using outdated Docker software

Thanks!

**Comment by stephen-turner** [comment]
Thanks for the comment. We're aware of this issue, but unfortunately as Docker Desktop is installed software, we can't fix old versions.

As this repository is for feature requests, and this is a bug report, I'm going to close this ticket.

**Comment by whitered** [comment]
@stephen-turner Do you have a corresponding bug report in a proper repository? The popup is extremely annoying and we need to get rid of it

**Comment by stephen-turner** [comment]
Unfortunately we can't fix it because it's in installed software. We can't go back and fix the version you already have on your machine.
