### ISSUE TITLE
Pause all containers to save battery

### ISSUE THREAD

**Issue by jakobjs** [docker/roadmap#226]
**Tell us about your request**
So when I unplug my new MBP from it's power brick and have my K8s cluster running in kind my battery can be empty in 15 minutes 😂

**Which service(s) is this request for?**
Docker Desktop 👍 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Shutting down Docker Desktop can take time even on fast hardware today if you have a bunch of containers running. Is it possible to add a Pause function that stops all machines but keeps everything in memory? The CPU usage is killing my battery.

**Are you currently working around the issue?**
No workaround, docker shutdown when moving to the conference room :(

**Comment by nebuk89** [comment]
@jakobjs thanks for the suggestion! We have discussed this before and it's a cool idea. Would you want a manual way to do this as well in the whale menu or just automated?

**Comment by jakobjs** [comment]
@nebuk89 A manual switch in the Whale menu would be nice plus an option in the config to toggle auto-pause on unplug.

**Comment by joe0BAB** [comment]
Please try out Docker Desktop version 4.2.0! It introduces pause/resume and can be triggered from the whale menu.
