### ISSUE TITLE
Give me option to disable auto updates completely

### ISSUE THREAD

**Issue by uspasojevic96** [docker/roadmap#228]
**Tell us about your request**
I want to disable all and every check, prompt and install.

**Which service(s) is this request for?**
Docker Desktop Mac

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I update my software only when i explicitly need it for my needs, other than that, everything stays on one version

**Are you currently working around the issue?**
Installing Docker 2.5.x as we speak

**Additional context**
This reminds me of Windows Update cancer

EDIT: And paying for basic feature is not an option, it's beyond bad decision

**Comment by briantopping** [comment]
Agreed. When I want an upgrade, I will ask for it. I know how to find it. 

A default that includes auto-updates is fine. That will cover the use case for users who somehow decided to install it and don't know why.

For the rest of us, please allow us to disable this noise.

I get that the team is crowdsourcing anomaly reporting to users that pay nothing, that the best way to "get something back from them is to nag them into smoke testing new software". 

Not sure what to say other than thanks for the efforts, but we'll probably move along soon if this continues to be a problem.

**Comment by robertsonai** [comment]
I completely agree here.  Version locking software is a common practice and
keeping uniform versions among all environments is extremely important.  I
manage my versions via MDM and do not want to have Engineers be harassed
with upgrade requests.

**Comment by Faheetah** [comment]
I'm sorry but this is poor ergonomics. I am in the middle of trying to hammer away at a bug in our software and the docker desktop app takes the liberty of splashing a notification right in the middle of my work that I should update right now, with the only option to be snoozing the notification. I cannot restart right now, I have containers I am actively working on, the alternative is to delay it tomorrow which I guarantee you will be some time in the middle of important work. Maybe you could argue that I should run the update later, but lets be honest here, that's not always going to happen. I'm sorry yall are prone to extra support burden from users not upgrading but being a single revision behind isn't good reason to continuously nag users to upgrade. More and more I am considering just rolling my own local container with docker as an alternative. There's times developers need to lock their enviroment and can't risk upgrading their tooling and having it break. It's frustrating that ubiquitous functionality is being hidden behind a paywall with Docker.

**Comment by briantopping** [comment]
They have conveniently left out the `command-H` from the menus. I've found it possible right click on the icon in the dock to hide it. 

Seems like someone could make an AppleScript that does this automatically. So much code, so little time.

**Comment by jedeleh** [comment]
I'd like to be able to choose which updates to download. Forcing an update unless you are a pro user (I assume "paid") is really bad form. My development environment is mine to work in and control. Make updates fully skippable.

**Comment by uspasojevic96** [comment]
Funny how there is no response from any member of docker

**Comment by Andrei997** [comment]
Awesome response from the Docker team! I love receiving the message to update to the latest version even though I do not want to. This is one of the best experiences I've had with a software as a developer! (sarcasm)

**Comment by joe0BAB** [comment]
Please checkout version 4.2.0! We have improved the update experience and will continue to do so. All update settings are free now and you can disable auto update check. Also the popup prompting to update when a new version is available has been removed.

**Comment by uspasojevic96** [comment]
> Please checkout version 4.2.0! We have improved the update experience and will continue to do so. All update settings are free now and you can disable auto update check. Also the popup prompting to update when a new version is available has been removed.

I just checked for updates, it offered 4.1.1 version

**Comment by joe0BAB** [comment]
> > Please checkout version 4.2.0! We have improved the update experience and will continue to do so. All update settings are free now and you can disable auto update check. Also the popup prompting to update when a new version is available has been removed.
> 
> I just checked for updates, it offered 4.1.1 version

It might take a bit longer depending from which geographical region you try to download but should be available latest in a couple of hours/minutes.
