### ISSUE TITLE
Support for BSD and Darwin

### ISSUE THREAD

**Issue by heroku-miraheze** [docker/roadmap#247]
**Tell us about your request**
We need to support Docker for BSD and Darwin.

**Which service(s) is this request for?**
Docker for BSD and Darwin.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Support BSD and Darwin.

**Are you currently working around the issue?**
Yes.

**Additional context**
Also support to install Docker in BSD and Darwin.

**Comment by justincormack** [comment]
Can you be clearer what you are asking for? Do you want to run Docker to build Linux containers under BSD/Darwin (you can do this with Docker for Mac on Darwin), or are you interested in the native engine to build native containers? In that case there has been various pieces of work for FreeBSD in the past on building a runc equivalent, and porting some of that ecosystem but this tends to be started every few years and never finished. For Darwin there are a number of technical issues (eg lack of bind mounts) and there is very little interest in native Darwin containers, soo little work has taken place; I think it is technically feasible but the infrastructure would have to be somewhat different from Linux containers.

**Comment by andrewcrook** [comment]
@justincormack   

I am wondering if the OP was thinking the same as me. If it would be possible to have a native Darwin Docker as opposed to having a Linux VM Base and QEMU. 

> or are you interested in the native engine to build native containers? 

> For Darwin there are a number of technical issues (eg lack of bind mounts) and there is very little interest in native Darwin containers, soo little work has taken place; I think it is technically feasible but the infrastructure would have to be somewhat different from Linux containers.

**Comment by stephen-turner** [comment]
I'm closing this ticket because we have no plans to work on it. There are no *BSD containers, and no signs that the community is going to create them. As I understand it, BSD does not provide the same ABI compatibility guarantees as Linux so it would be difficult. Using Linux containers in Docker Desktop is your best bet.
