### ISSUE TITLE
Is there a way to obtain all public available image names from Docker Hub? 

### ISSUE THREAD

**Issue by martinstraesser** [docker/roadmap#258]
For a data analytics study, I would like to analyze as much images from Docker Hub as possible.

I'm currently investing some effort in a web crawler, however, I am facing the problem that the results from an explicit search or from the explore page are limited to 20 pages, but it says that ` 8.249.493 available images` are stored on Docker Hub. 

Is there any way to get the image names for all public available images from Docker Hub? Or to enlarge to number of pages for the search results? 

Thanks for any feedback.

**Comment by justincormack** [comment]
There is no supported way to do this. Due to the scale of Docker Hub you are likely to hit our rate limits if you try this. There are a _lot_ more than 8m images.

**Comment by stephen-turner** [comment]
Closing per Justin Cormack's reply.
