### ISSUE TITLE
Customising  DockerDesktop virtual machine

### ISSUE THREAD

**Issue by Tenakh** [docker/roadmap#260]
**Tell us about your request**
Security team force us to insert security agent and run-time vulnerabilities scanner into DockerDesktop virtual machine.

**Which service(s) is this request for?**
DockerDesktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
DockerDesktop user can lunch containers with malware and vulnerabilities. So development infrastructure could be compromised. To prevent this, we use security scanners (own). 
Now we are looking for a legal solution to customise  DockerDesktop virtual machine.

**Are you currently working around the issue?**
We are exploring LinuxKit

**Additional context**

**Comment by nebuk89** [comment]
@Tenakh thanks for the feedback, we are currently looking at what might be good to improve the security of Desktop. Would you be interested in jumping on a call to talk through your use cases further? If so drop me an email on bengotch@docker.com

**Comment by stephanierifai** [comment]
Thanks for the feedback @voliveirajr ! I will pass back the feedback on documentation to the team as well :)

**Comment by Tenakh** [comment]
Hello!
I'm looking for a way to add security components into docker vm. Like
iptables setting useful for our network or some other security packages,
with ability to configure them.

Right now, i'm working around installing DockerDesktop for Mac ovet
network.
If you have usefull techniques, please share with me.

Thx.

пт, 24 сент. 2021 г., 18:14 Ben De St Paer-Gotch ***@***.***>:

**Comment by christophermclellan** [comment]
Thanks for submitting your issue. We are working hard on improving the visibility and security controls that organisations have over the Docker Desktop Linux VM and will ship our first version of this in the upcoming Docker Desktop v4.13 release. As such, I'll close this issue. We won't be providing the ability to create customized VMs etc.
