### ISSUE TITLE
Support for multi-users scenarios on HPC

### ISSUE THREAD

**Issue by BenjaminChoou** [docker/roadmap#266]
**Tell us about your request**
I expect that docker can support multi-users scenarios on High-Performance Cluster. Specifically, I expect docker can provide isolation to limit users' behaviors and separate images and containers created by different users on the server. So far, everyone can access (attach, start, stop) any container that exists. To my understanding, running docker with a user namespace does not provide mentioned features.

**Which service(s) is this request for?**
Docker engine for ubuntu

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have a multi-GPUs server for our lab. Even though the docker is running with a user namespace to avoid getting root permission, everyone in the server can still attach containers created by anyone. That's quite insecure.

**Comment by AkihiroSuda** [comment]
There is already rootless mode for this usecase 

https://rootlesscontaine.rs/getting-started/docker/

**Comment by nebuk89** [comment]
@BenjaminChoou Closing this as we believe rootless addresses your need :)

**Comment by BenjaminChoou** [comment]
> There is already rootless mode for this usecase
> 
> https://rootlesscontaine.rs/getting-started/docker/

Thanks.
