### ISSUE TITLE
[Docker Desktop] Admin Management of Docker Desktop Settings

### ISSUE THREAD

**Issue by voliveirajr** [docker/roadmap#267]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
For distribution to developers in some cotrolled environments is desirable have some system of feature toggling, I would like to prevent the users to setup proxy, dns, etc or provide them one and protect this configurations.

### Expected behavior
Users can configure all the settings and there is no option to restrict or pre-setup in a protected mode.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by osariel** [comment]
We are in the process of evaluating docker desktop for windows. We are looking at the business subscription as it offers a lot of the security and centralised controls that satisfy regulatory requirements, and the firm's security architecture. Do you have an example design diagram of what an enterprise implementation may look like, perhaps with the most security, even if it is just theoretical and many of the features may not make it to the final solution.
Thanks

**Comment by stephanierifai** [comment]
Hi @osariel, want to drop me a line at steph.rifai@docker.com so we can chat about what you are looking for a bit further? We are currently in the process of validating this feature and would love to learn more about your requirements and what we are thinking to see if the direction we are heading would meet your needs.

**Comment by osariel** [comment]
> Hi @osariel, want to drop me a line at [steph.rifai@docker.com](mailto:steph.rifai@docker.com) so we can chat about what you are looking for a bit further? We are currently in the process of validating this feature and would love to learn more about your requirements and what we are thinking to see if the direction we are heading would meet your needs.

Hi Steph. Thanks. I have sent an email to you. A two days ago.

**Comment by stephanierifai** [comment]
Thank you! Yes, sorry for my slow response, want to make sure I get you the appropriate details for the items you have mentioned :)

**Comment by davedivilly** [comment]
Can Enterprise customers (Docker Business subscription) enable/disable certain feature in Docker Desktop via their Organisation setup in Docker Hub. 
For example: 
 - We want to disabled 'usage statistics' being sent when an internal user starts Docker Desktop. This is a requirement for our company that the publisher not track any usage or analytics of their software. 
 - Can we also disable sending a email notification when a user is removed from an organisation.

**Comment by stephanierifai** [comment]
@davedivilly Great feedback! 

As part of the admin control plane for Docker Desktop settings, we do plan to make any of the available settings (including turn of usage statistics) available for admins to set defaults and prevent users from changing it, though no definite timeline for when this will be available.

We weren't planning on addressing the email notification you mentioned for the MVP, but would love to chat more with you about this and other potential use cases. If you're open to chatting, definitely drop me an email:steph.rifai@docker.com!

**Comment by Lotusshaney** [comment]
Im very interested in this too for my companies needs.  The ability to lock down/manage settings like proxy settings is strongly neeeded.

**Comment by stephanierifai** [comment]
@Lotusshaney - thanks for the feedback! We are looking into solutions for the use case around proxy settings currently and have some questions around how companies are using proxy settings now that would help us inform our solution a lot. Would you be willing to give some input? If so feel free to reach out at the email: steph.rifai@docker.com ! That would be a huge help 🙏

**Comment by christophermclellan** [comment]
Hi folks, we're almost there on this one. Early Access will be available soon. Any further questions, please ping me here or at chris.mclellan@docker.com. Thanks !

**Comment by christophermclellan** [comment]
Thanks for creating this issue @voliveirajr. 

We've shipped Settings Management this week, docs are here - https://docs.docker.com/desktop/hardened-desktop/settings-management/

To read more about the Hardened Docker Desktop security model for Docker Business customers, please see here - https://docs.docker.com/desktop/hardened-desktop/.

Are there any other settings that you'd like to see managed via Settings Management ?

**Comment by voliveirajr** [comment]
Thank you Christopher, glad to know that.
I will sync this up with the team to review our requirements that are still open and let you know
