### ISSUE TITLE
osxfs: character device file support

### ISSUE THREAD

**Issue by CamJN** [docker/roadmap#268]
**Tell us about your request**
Make debootstrap work on osxfs by adding character device file support.

**Which service(s) is this request for?**
osxfs

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I need character device file support in order to build linux packages (rpm/deb). 

**Are you currently working around the issue?**
No, I have to use docker on linux to build packages.

**Additional context**
https://github.com/docker/for-mac/issues/291

**Comment by justincormack** [comment]
cc @djs55 as you responded on the other issue

**Comment by christophermclellan** [comment]
Hi @CamJN, thanks a lot for posting this issue. I hope that the solutions @djs55 posted above have been helpful. For the time being, I'll close this issue. 

Chris
