### ISSUE TITLE
[Docker Desktop] - Feedbacks gathering - Networks view

### ISSUE THREAD

**Issue by glours** [docker/roadmap#270]
**Tell us about your request**
We want to know if having a dedicated view to manage Networks would be a valuable feature to you?

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Providing a great user experience to view and manage networks via Docker Desktop 

**Are you currently working around the issue?**
A sample of what a Network view could look like

https://user-images.githubusercontent.com/705411/136391684-b52095da-f81f-4a54-9532-59c43b3766e1.mp4

**Comment by mikesir87** [comment]
First off, I love the idea of being able to see the networks. But, I think one further step than just having a list of networks would be to see something visually. This would help a lot for apps/containers that might span multiple networks. For example...

- A proxy container in a proxy network. Who can it talk to?
- What can each of those containers talk to?
- And so on...

Being able to graphically see the connections (with network boundaries in place) will help folks quickly understand and see how the networks work.

**Comment by Coubiac** [comment]
Open in wireshark

**Comment by christophermclellan** [comment]
Hey @glours, i'll close this issue as it's been open for a while and some feedback has been gathered. Let me know if you'd like me to reopen.
