### ISSUE TITLE
[Feature Request][Docker Desktop] Window Resizing

### ISSUE THREAD

**Issue by Cortrah** [docker/roadmap#279]
It drives me nuts that the docker desktop dashboard for windows won't allow the window to be anything less than 2500 pixels wide. There is no functional need for this to change. It's not like there is some 240x240 pixels of monitoring information that I feel I need to view in the corner of a screen. It just drives me nuts when I'm checking out and organizing what I've got running that I can't make it small. Do with this information as you will and be well :D.

**Comment by stephanierifai** [comment]
Hi @Cortrah, do you mind me asking what version you are on? We recently introduced the ability to resize the window in DD 4.1.0, I wonder if it is working for you or if you want to make it even smaller than what we've introduced?

**Comment by Cortrah** [comment]
Thanks Stephani,

I just updated to the new version. Much better!

**Comment by stephanierifai** [comment]
Yay glad to hear it!! Thanks for submitting your feedback, it helps us get things like this prioritized :) Look forward to hearing your ideas in the future :)
