### ISSUE TITLE
Open Source Docker Desktop

### ISSUE THREAD

**Issue by robd003** [docker/roadmap#285]
**Tell us about your request**
Release the source code for Docker Desktop

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The community could help fix bugs faster.

**Are you currently working around the issue?**
I'm using podman

**Comment by nebuk89** [comment]
Thank you for the request, we have no plans to open source Docker Desktop at this time. If you are interested in contributing to Docker Engine this remains open source and we would love your input.
