### ISSUE TITLE
Docker Desktop Extensions

### ISSUE THREAD

**Issue by amyb12345** [docker/roadmap#290]
**Tell us about your request**
We're interested in hearing from the Docker community what sort of integrated extensions to Docker Desktop would be helpful to you? Why?
What additional, complementary development tools do you install alongside Docker Desktop (perhaps even setup alias's to) to complete your development environment? Why?

**Which service(s) is this request for?**
Docker Desktop

**Comment by AJRepo** [comment]
A "ZeroTrust" model. Or in other words, track changes in containers BEFORE you turn them on not just between downloaded versions but also the difference between the image released by original vendor vs what is downloaded from the docker hub.

**Comment by asifgit** [comment]
Is it possible to build my docker container using an intent-based approach? (easy through a front-end)

**Comment by amyb12345** [comment]
@asifgit Thanks for the feedback! Would you be able elaborate more or provide an example of what you are thinking?  Or if you know of any tools that do this now, I'd love to hear about them!

**Comment by pcjmfranken** [comment]
Could we have these extensions be disabled by default, possibly installed only on demand? My areas of concern being security and provisioning/control overhead.

**Comment by kaznovac** [comment]
make Snyk an optional extension - i rarely use it, and it's a ton of small files

**Comment by SergioSuarezDev** [comment]
Extensions are not working now on 4.9.0 (80466) MacOS?

Can't see the option on this version:

<img width="1262" alt="Captura de Pantalla 2022-06-04 a las 12 36 04" src="https://user-images.githubusercontent.com/3636232/171995512-5d87f8d2-0d8a-4e8e-8fdc-eea34c9b9d60.png">

**Comment by felipecruz91** [comment]
Hi @SergioSuarezDev, thank you for reporting the issue. 

This thread is used to discuss what integrations the community would be interested in having as part of Docker Extensions. For technical issues related to Docker Extensions, could you please open a new issue in the [Extensions SDK repository](https://github.com/docker/extensions-sdk/)? We'd also need the [in-app diagnostics](https://docs.docker.com/desktop/windows/troubleshoot/#in-app-diagnostics) to help us replicate the problem on our side.

**Comment by abunch** [comment]
I'd like to see two extensions:
1) An extension FIXES the IO performance issues on the Mac platform now that you're charing for the app.
2) An extension that STABILIZES the existing docker desktop - maybe the extension should do more QA before it allows the release to be released?

**Comment by amyb12345** [comment]
We've moved this to GA with the release of Docker Desktop 4.16
