### ISSUE TITLE
Remove Rosetta as requirement for Docker Desktop on Apple Silicon 

### ISSUE THREAD

**Issue by jfernandezr** [docker/roadmap#294]
It's been some time now since the first release of Docker Desktop supporting Apple Silicon, but it stills holds Rosetta as a requirement.

Apple has always said that Rosetta is a temporary translation layer allowing software developers to have enough time to deliver specific ARM versions, and they will shut it off after some months.

Meanwhile I've been using remote development with Visual Studio Code against a remote machine running Linux x64, but this is not an ideal situation. Docker has become a central piece on any kind of software development, and Mac is one of the preferred ecosystems used by developers. I think that fully native M1 support should be put as top priority in the roadmap.

Thanks!!

**Comment by stephen-turner** [comment]
Thank you for your comments, @jfernandezr. This has already been done in Docker Desktop 4.3. https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-430

**Comment by stephen-turner** [comment]
No worries, it's new, we only just released it last week!
