### ISSUE TITLE
[Docker Desktop] Replace SAMBA with GRPCFuse

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#30]
"**Tell us about your request**
Introduce a new file sharing implementation that replaces Samba, CIFS, and Hyper-V networking. 

**Which service(s) is this request for?**
Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The new implementation offers improved I/O performance. Additionally, when using the new file system:

Users don’t have to expose the Samba port, and therefore do not experience issues related to IT firewall or drive-sharing policy.
There is no need to provide user credentials to Docker Desktop. File access rights are automatically enforced when accessing mounted folders through containers.

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**
"

**Comment by hinews** [comment]
Hi @nebuk89 
In which version it of Docker Desktop it will be available?

**Comment by gmsantos** [comment]
Hi @hinews 

You can see some details in this [release notes](https://www.docker.com/blog/new-filesharing-implementation-in-docker-desktop-windows/).

**Comment by nebuk89** [comment]
@hinews sorry I missed this, this is in stable for all non-WSL 2 users (they can use WSL2) and is on by default, we have removed the Samba integration now!
