### ISSUE TITLE
Make Docker Desktop for Mac app icon a rounded-rectangle to match Big Sur style guide

### ISSUE THREAD

**Issue by rakleed** [docker/roadmap#306]
**Tell us about your request**
Please update the macOS app icon according to Big Sur's guidelines - https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon.

**Which service(s) is this request for?**
Docker Desktop for Mac

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The current icon does not look good against the background of other icons, and also does not comply with HIG.

**Are you currently working around the issue?**
I can set a different icon for the app myself (for example, from https://macosicons.com/docker), but for some reason the icon in my Dock does not change. It also needs to be reinstalled after each app update.

**Additional context**
https://github.com/docker/for-mac/issues/3793#issuecomment-719278910 and following comments.

**Comment by stephanierifai** [comment]
Hi! We shipped this in 4.8, check it out and let us know what you think!
<img width="61" alt="Screen Shot 2022-05-26 at 5 55 13 PM" src="https://user-images.githubusercontent.com/85884197/170586406-efcb2fe8-05b6-423c-8ed4-9060a721f162.png">
