### ISSUE TITLE
Unattended install of Docker Desktop (automatically accept license and suppress notification about WSL 2 installation)

### ISSUE THREAD

**Issue by nbdinara** [docker/roadmap#307]
I am trying to do unattended install docker through PowerShell. 

I have found these flags, but they do nothing: 
install --accept-license --unattended

I want these agreements on the screenshot to be accepted automatically:
![agreements](https://user-images.githubusercontent.com/35890180/151410382-bb9cceee-488d-44d0-8aa9-fab3a9124deb.png)

I want this notification to be suppressed
![wsl](https://user-images.githubusercontent.com/35890180/151410410-7e5d3298-6739-4fec-b9c5-5c91cc8cd351.png)

I need this solution for Docker Desktop for Windows machines. 

Could you please provide me instruction how to do that or add these features if you don't have them yet.

**Comment by jgresham** [comment]
I am developing an app on all platforms which has a dependency on Docker and I would like my app to be able to install Docker (with user permissions) without requiring the user to do as little as possible. Therefore, I am very interested in this feature!

@jimichoe thanks for making note of the flags

**Comment by stephen-turner** [comment]
Yes, one popup as non-admin is expected.

Glad to hear it's working: I'll mark this ticket as Done now.

**Comment by saowu** [comment]
Currently, installing docker desktop on Windows 10 requires the following steps:

1. Enable Hyper-V.
2. Enable wsl2 (Windows based Linux subsystem).
3. install docker desktop.
4. You may need to upgrade wsl2.[https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi](wsl_update_x64.msi)

**Comment by saowu** [comment]
> 目前，在 Windows 10 上安装 docker desktop 需要以下步骤：
> 
> 1. 启用 Hyper-V。
> 2. 启用 wsl2（基于 Windows 的 Linux 子系统）。
> 3. 安装docker桌面。
> 4. 您可能需要升级 wsl2。[https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi](wsl_update_x64.msi)

It's really troublesome and easy to waste a lot of time.
