### ISSUE TITLE
SAML 2.0 + SCIM for Automatic Provisioning

### ISSUE THREAD

**Issue by vincentbriglia** [docker/roadmap#309]
**Tell us about your request**
We are a large organization where external consultants join and leave fairly regularly. SCIM would allows us to have automatic provisioning and de-provisioning of users so that removing people isn't a manual process. 

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

These are related in how could enable deprovisioning programmatically, but SCIM would be the standardized way of deprovisioning with SAML SSO is implemented.
- [ ]  https://github.com/docker/roadmap/issues/261
- [ ] https://github.com/docker/roadmap/issues/20

**Are you currently working around the issue?**
currently a manual process

**Comment by tehautanop** [comment]
https://github.com/docker/roadmap/issues/316

**Comment by damomi** [comment]
I can see this was Shipped 6 days ago. Is there any documentation for it so we can read it and at some point start using it?
Regards

**Comment by izzychu** [comment]
> I can see this was Shipped 6 days ago. Is there any documentation for it so we can read it and at some point start using it? Regards

We are in early access stage and here is the current documentation link (will be updated again in July)! https://docs.docker.com/docker-hub/scim/

**Comment by damomi** [comment]
Hi team, 
Can you please confirm that SCIM is now available to be use. Is the documentation up to date so we can start using it?

**Comment by stephanierifai** [comment]
Hi @damomi, yes! You can check out the [blog here](https://www.docker.com/blog/new-scim-capabilities-for-docker-business/) and [documentation](https://docs.docker.com/docker-hub/scim/).
