### ISSUE TITLE
[Docker Desktop] New Electron based UI

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#31]
**Tell us about your request**
Replace the previous native menus in Docker Desktop with a set of new re-designed electron windows allowing a single UI across both platforms

**Which service(s) is this request for?**
Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Reduces engineering cost of maintaining 2 UIs and reduces ongoing cost to add/change features as we have a single cost base for UI

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**

**Comment by 0zirix** [comment]
Please god don't use electron. It's really poor in terms of performance. I know that it's cheaper for your Boss, but believe me, the engagement of the users if you develop the ui with something decent and cross-plateform, like Qt.
