### ISSUE TITLE
Make buildx available in official Docker images

### ISSUE THREAD

**Issue by wedi** [docker/roadmap#322]
**Tell us about your request**
Buildx is the way to go forward and take advantage of the great features BuildKit brought to Docker. buildx is available on every (most?) platforms by default when you install docker with one notable – and somewhat ironic – exception: the official Docker images. The official Docker images seem to be the only distribution packages that do not ship with buildx (and compose) by default. Let that sink in.  
That is strange in itself, but it's a real bummer when you start to transition to buildx locally because it's seemingly available everywhere by default and prepare to move on to CI. All shiny new workflows are broken and you need to revert back to regular builds. Not only does this hinder the adoption of buildx (and composer), this burns countless developer hours, judging by the number of people who reacted on the related issues.

**Which service(s) is this request for?**
Official Docker images on Docker Hub, especially the Docker-in-Docker variants ( tagged [dind](https://hub.docker.com/_/docker?tab=tags&page=1&name=dind)).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I would like to use buildx in CI without a hassle. At the moment, this requires me (and everyone who wants to use buildx in a Docker-in-Docker CI workflow) to build and maintain a variant of the official Docker images from Docker Hub – or give up on the advantage of using an official image and rely on a friendly guy from the internet.

**Are you currently working around the issue?**
Yes, I have created and regularly check and update a custom version of the official Docker images.

**Additional context**
[The first trace](https://github.com/docker-library/docker/issues/156) of this request dates back to 2019 [and](https://github.com/docker/buildx/issues/647) [there](https://github.com/docker/buildx/issues/305) [have](https://github.com/docker-library/docker/issues/243) [been](https://github.com/docker-library/docker/issues/313) [multiple](https://github.com/docker/buildx/issues/349) [duplicates](https://github.com/docker/buildx/issues/553).
There is a more than two years old [pull request](https://github.com/docker/docker-ce-packaging/pull/415) to resolve [the current blocker](https://github.com/docker-library/docker/issues/156#issuecomment-489245333) and a member of the Docker team provides an [image](https://github.com/crazy-max/docker-docker) as a "temporary" workaround since December 2020 with [100K+ pulls](https://hub.docker.com/r/crazymax/docker).

I have already [asked](https://github.com/docker-library/docker/issues/156#issuecomment-1050961717) to reconsider this a few weeks ago and stumbled over this roadmap repo today.

You added [buildx support to GitHub actions](https://github.com/docker/roadmap/issues/122) in fall 2020. It would be very kind if you could add buildx to the official Docker images in spring 2022.

**Comment by ddelange** [comment]
In the meantime there is [`jdrouet/docker-with-buildx:alpine`](https://hub.docker.com/r/jdrouet/docker-with-buildx) mentioned in this [Docker blog post](https://www.docker.com/blog/multi-arch-build-what-about-gitlab-ci/)

Not official of course...

**Comment by maniator** [comment]
Can also use https://hub.docker.com/r/maniator/docker-with-buildx/ 👍

**Comment by maniator** [comment]
I finally fixed auto builds with GitHub actions, not sure why they stopped....

**Comment by chris-crone** [comment]
A PR is up to implement this :) https://github.com/docker-library/docker/pull/361

**Comment by wedi** [comment]
This has been merged in https://github.com/docker-library/official-images/pull/12403. Big thanks to everyone involved. ❤️

**Comment by a-a-k** [comment]
@wedi could you please tell me evenually which official docker image contains buildx now?

**Comment by tianon** [comment]
@a-a-k that'd be https://hub.docker.com/_/docker (specifically the `cli` variants if all you need is buildx); it was just updated to the newly released 0.11.0
