### ISSUE TITLE
Add "Hide" to Docker Desktop

### ISSUE THREAD

**Issue by kohlab** [docker/roadmap#325]
Docker is the only app in my Applications folder on the Mac that I can't hide. When I open the dashboard it gets in the way. Please add this.

**Comment by stephanierifai** [comment]
Hi @kohlab are you looking for "command + h" to work with the docker dashboard, or something else?

**Comment by kohlab** [comment]
Hi @stephanierifai, yes, with its corresponding menu item.

**Comment by stephanierifai** [comment]
I think that not being available might be a bug, would you be able to let me know what version you are on of Docker Desktop?

**Comment by snapdoor** [comment]
Sure thing. I'm on 4.6.1 (76265) for macOS.

**Comment by kohlab** [comment]
Sure thing. I'm on 4.6.1 (76265) for macOS.

**Comment by stephanierifai** [comment]
Thanks, will check it out!

**Comment by nunocoracao** [comment]
Hello @kohlab, can you confirm that this is fixed so that I can close the ticket.

**Comment by kohlab** [comment]
Hi @nunocoracao, yes, fixed. Thank you.
