### ISSUE TITLE
Networking issues with Lando/Docker and OSX 12.3 - `lando composer update` fails 100% of the time on drupal core...

### ISSUE THREAD

**Issue by alphex** [docker/roadmap#326]
This is a truncated (at the end) list of things composer (version 2) is doing, when I run `lando composer update` on my drupal projects.

```
 - Upgrading phpunit/phpunit (9.5.17 => 9.5.19): Extracting archive
  - Upgrading composer/composer (2.2.7 => 2.2.9): Extracting archive
  - Upgrading drupal/core-dev (9.3.7 => 9.3.9)
  - Upgrading drupal/core-recommended (9.3.7 => 9.3.9)
  - Upgrading drupal/menu_block (1.7.0 => 1.8.0): Extracting archive
  - Upgrading drupal/svg_image (1.15.0 => 1.16.0): Extracting archive
 7/8 [========================>---]  87%    Update of drupal/core failed

In Filesystem.php line 332:

  Could not delete /app/vendor/composer/eabc945e/drupal-core-86b0c44/profiles/standard:

```

It will go through MANY items, in this example it says 7 of 8... I've seen this happen with 100+ items getting touched by composer.

In all cases, I get a filesystem.php error very similar to what you see there, ALWAYS related to core, but never the same file.

When I run composer directly on my localhost,  it runs flawlessly (and MUCH faster - which I understand may just be the nature of NFS ...)

Has anyone else seen this since updating to OSX 12.3?

This happens, 100% of the time with my lando projects in drupal right now.

I _just_ before generating the error above, 100% removed lando, and docker, and all images and all containers -- thinking maybe something in lando and docker's file system is broken...     But I'm still getting the error with a fresh 3.6.2 install.

Any thoughts?
Other people suffering this?

Thank you!

**Comment by alphex** [comment]
This might be in the wrong place, please let me know if this needs to be asked somewhere else.

**Comment by RosieGarcia** [comment]
Thanks @alphex, yes this may be better suited in our issue tracker for mac: https://github.com/docker/for-mac/
