### ISSUE TITLE
Read System Proxy

### ISSUE THREAD

**Issue by stephanierifai** [docker/roadmap#338]
**Tell us about your request**
Have Docker Desktop respect the operating system level proxy settings rather than having to manual configure proxy settings.

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When working in a corporate environment, setting up proxies is required to use Docker Desktop. 
Related to:
https://github.com/docker/for-win/issues/5447

**Are you currently working around the issue?**
Setting proxy configuration manually in Docker Desktop settings

**Additional context**
N/A

**Comment by linuxem** [comment]
On ubuntu, it is needed too in case there is no proxy the docker-desktop does not pull images
