### ISSUE TITLE
Deprecate Proxy Manual Configuration

### ISSUE THREAD

**Issue by stephanierifai** [docker/roadmap#339]
**Tell us about your request**
Now that Docker Desktop will respect the system proxy (See https://github.com/docker/roadmap/issues/338), we would like to deprecate manual configuration of the proxy in a future version. We'd like to understand if users have use cases for using a manual configured proxy that is different from your system level proxy. 

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Related to https://github.com/docker/roadmap/issues/267, there is interest in preventing manual configuration of Docker Desktop proxies, but still a need to set proxies which is why we introduced reading the system proxy. 

**Are you currently working around the issue?**
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Additional context**

**Comment by pcjmfranken** [comment]
I sometimes use it in a certain way to prevent Docker from sneaking out usage telemetry trough the container connections.

You should really start respecting the telemetry opt-out, these connections to `api.segment.io`, `sessions.bugsnag.com`, `notify.bugsnag.com`, `api.wootric.com` and who knows where else really shouldn't be happening.

**Comment by dandrzejewski** [comment]
To clarify - are you planning to remove proxy configuration *entirely* or just from the UI - e.g., will I still be able to configure proxies manually in JSON?

I can't go into a lot of detail because it's work-related, but I sometimes need to use proxies that are not the defaults from OS-level auto-discovery.

**Comment by dandrzejewski** [comment]
You may also run into scenarios where users are on networks that do not support proxy auto-discovery and they may require manual configuration.  My guess is this is not common.

**Comment by paulchambers** [comment]
My team also relies on manual proxy configuration. The OS level proxy config is a fairly complex pac file so docker just reading the  system proxy host/port wouldn't work for us.

**Comment by awynnejo** [comment]
I also rely on manual proxy configuration, happy if it is removed from the GUI but would still need somewhere to set it.
