### ISSUE TITLE
Unattended setup option to suppress desktop icon

### ISSUE THREAD

**Issue by blindzero** [docker/roadmap#340]
**Tell us about your request**
Please add some option for unattended installs to prevent desktop icon 

**Which service(s) is this request for?**
Docker Desktop for Windows

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Honestly, who needs a desktop icon for docker? ;-)

**Comment by christophermclellan** [comment]
Thanks for submitting your issue. This is not something Docker is considering working on.

**Comment by blindzero** [comment]
😞
