### ISSUE TITLE
Clarification on DockerDesktop installation

### ISSUE THREAD

**Issue by Bhuvanaprabha** [docker/roadmap#343]
Hello Team,
Need support on Docker Desktop application installation and uninstallation from Docker Engineers.
 
1.“Support option” should be disabled under “Troubleshoot”. User should not Click on “Get support” from the application.
2.Metering of the usage by end users should be visible for the admins on the Docker Hub. This way we can easily remove licenses that is not used for a period of 30/60 days.    
3.When users login to Docker Hub, they can view other team members and to which group they have been added from their account. This is not a standard behavior and we would prefer to keep the data confidential. We need steps/process how to hide the data.
4.When creating the repository there are two options: Public and Private.
We would like to know how exactly the Public option works out.
5.We require an Uninstaller setup file, which handles the removal of all versions of manually installed Docker software from user’s machine along with residues. 
The provided Uninstaller will be handled in the PowerShell script in our environment to deploy it via SCCM. While handling this Uninstaller, any other applications should not be affected.

Thank You!

Regards,
Bhuvanaprabha

**Comment by Bhuvanaprabha** [comment]
Hello Team, 

I would like to request the team to provide clarification on higher priority. Also add up the additional clarification points. 
Here are the list of points which we require PowerShell commands :

1.	Need to suppress the Agreement terms. User should not get this pop-up while launching the application for the first time. By default, application should be launched without asking for “Check mark” and “Accept”.
2. 	After launching the application, there is an option to “Check for updates” under "Settings". We do not prefer to automatically do updates from customer’s side. We need PowerShell script to disable all the options in Software Updates including the “Upgrade” option on the top right side.
3.     “Support option” should disabled under “Troubleshoot”. User should not be able to Click on Get support from the application.

Thank You!

Regards,
Bhuvanaprabha

**Comment by stephen-turner** [comment]
@Bhuvanaprabha As discussed in our phone call, the request for WSL 2 silent install is Microsoft's code not ours, but I have forwarded your request to them.

**Comment by christophermclellan** [comment]
Closing as not planned given Stephen's clarification above. Thanks for submitting this issue.
