### ISSUE TITLE
Docker Desktop Portainer extension dynamic ports

### ISSUE THREAD

**Issue by antoniobergas** [docker/roadmap#344]
**Tell us about your request**
Portainer extension have a configuration to change the ports that use for running

**Which service(s) is this request for?**
Docker Desktop Extensions

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have a containers group with minIO that we need to run in port 9000 and gets conflicts with the Portainer extension because it's using the same port and you cannot change it

**Are you currently working around the issue?**
I tried to run the Portainer passing another port but without luck

**Additional context**
No additional context

**Comment by amyb12345** [comment]
Hi, Thanks for making us aware of this challenge.  We've passed this feedback along to Portainer and will keep you updated on any changes that they make.

**Comment by pebell** [comment]
Same problem here. Need to be able to use port 9000 on my system; will have to disable the Portainer Docker Desktop Extension until the port it uses is configurable.

**Comment by amyb12345** [comment]
Portainer plans to fix this in one of their upcoming releases. We will let you know as soon as this has been addressed.

**Comment by SpiReCZ** [comment]
Our company VPN/Proxy uses port 9000, thx for addressing this issue.

**Comment by marcelo-ochoa** [comment]
There will be good to have the availability of defining environments vars prior to install the extension.
So on the extension docker-compose.yml a definition like:
```
     ports:
      - ${APP_HTTP_PORT:-9880}:9880
```
allows user to override the default port used by the extension.
Marcelo.

**Comment by amyb12345** [comment]
In talking with Portainer, yesterday's release included the removal of port 8000.  It is expected that in their mid October release, ports 9000 & 9443 will be changed to higher numbered ports. I'll update once this is released.

**Comment by antoniobergas** [comment]
Sorry for the delay. Thanks a lot to everyone involved to fix it 😊

Cheers
