### ISSUE TITLE
[Docker Extensions] Add Search to Marketplace

### ISSUE THREAD

**Issue by amyb12345** [docker/roadmap#346]
**Tell us about your request**
Add search capabilities to Docker Extension Marketplace

**Which service(s) is this request for?**
Docker Extensions

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As the list of extensions grows, we want to provide developers with a way to find extensions.  We also want to allow developers to search by keywords to find extensions to help solve daily challenges. 

**Are you currently working around the issue?**
Scrolling through the list is the only available option right now. 

**Additional context**
N/A

**Comment by andrei-z-albu** [comment]
Hi! I'm happy to share that search capabilities have been added to Docker Extension’s Marketplace with the new release of Docker Desktop 4.12.0. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by amyb12345** [comment]
Released in Docker Desktop 4.12!
