### ISSUE TITLE
Add option to open devtools under debugging in Docker Desktop

### ISSUE THREAD

**Issue by jrj2211** [docker/roadmap#376]
**Tell us about your request**
Since Docker Desktop is now electron, it would be nice to have a button to enable the devtools in Docker Desktop UI under the "debugging" menu. 

**Which service(s) is this request for?**
Docker Desktop UI

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm currently having an error with "Dev Enviroments Preview" where the UI is just returning "Error [object Object]". Not a particularly useful error and I'm guessing there's some useful output in the dev console for figuring out what's going on. Would help provide better feedback when testing these new features

**Are you currently working around the issue?**
No workaround that I know of. Both F12 and ctrl-shift-i do not work to open dev tools.

**Additional context**
Example of error:
![image](https://user-images.githubusercontent.com/6005836/173220889-994c99e3-8006-41ff-8157-dd062d071cb1.png)

**Comment by little-gu** [comment]
How to open devtools
