### ISSUE TITLE
Show/hide timestamps in dashboard's container log view

### ISSUE THREAD

**Issue by Dids** [docker/roadmap#386]
**Tell us about your request**
A new button in `Dashboard -> Container -> Logs`, which simply toggles showing additional timestamps on and off per line in the log.

**Which service(s) is this request for?**
Docker Desktop (macOS)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When working with containers that do not implement their own console/stdout logging with timestamp support, this would provide invaluable insight into time sensitive issue handling and debugging, straight from the dashboard app.

**Are you currently working around the issue?**
No.

**Additional context**
No additional context necessary, as this is a fairly trivial feature.

**Comment by stephanierifai** [comment]
Hi! This is now available in version 4.14 and above! Let us know what you think :D 
<img width="1258" alt="Screen Shot 2022-12-06 at 10 59 41 AM" src="https://user-images.githubusercontent.com/85884197/205961055-6244994b-587c-4da0-9d8d-6be6b852104b.png">
