### ISSUE TITLE
GUI in CLI

### ISSUE THREAD

**Issue by pixman92** [docker/roadmap#391]
A feature for running GUI apps through Docker CLI. To simply run a list of GUI apps from the command line. Like Firefox or GIMP.

It's really complicated to get all the right libraries together to make a GUI app work. Let's simplify this to a few CLI commands.

**Comment by stephanierifai** [comment]
Hey @pixman92 super interesting idea, i'd love to learn more about your use case. If you'd like to find a time to chat feel free to ping me at steph.rifai@docker.com!

**Comment by nunocoracao** [comment]
Hello @pixman92 closing this ticket since no info was added in the last year. Feel free to add more information and I'll be happy to re-open it and discuss. Thanks
