### ISSUE TITLE
[Docker Extensions] - Backup and share volumes

### ISSUE THREAD

**Issue by amyb12345** [docker/roadmap#394]
**Tell us about your request**
Provide an extension that allows for users to backup and share volumes

**Which service(s) is this request for?**
Desktop, Docker Extensions

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
While developing, testing, or running containerized apps locally, developers may require to use a well-defined dataset. For instance, starting a Postgres database with a prepopulated list of customers; debugging an issue when inserting a new record in a production database, or simply sharing your application state with a teammate. Furthermore, you are always one “system prune” away from loosing everything you were working on.

At the moment, to export the contents of a volume, you have to type some docker commands in a terminal or run scripts built by the community. The same applies if you want to import files into a volume, create a backup or share it.

**Are you currently working around the issue?**
Not backing up volumes/using scripts to re-create them

**Additional context**
N/A

**Comment by BretFisher** [comment]
👋 Putting these here for now:

Vackup script: https://github.com/BretFisher/docker-vackup
@felipecruz91's Extension based on that idea: https://github.com/felipecruz91/vackup-docker-extension

**Comment by amyb12345** [comment]
Available for installation here: [https://hub.docker.com/extensions/docker/volumes-backup-extension](https://hub.docker.com/extensions/docker/volumes-backup-extension)
