### ISSUE TITLE
[Hub] Export Users

### ISSUE THREAD

**Issue by nunocoracao** [docker/roadmap#401]
**Tell us about your request**
Export users list from an organization in Docker Hub. Add option to export DockerHub organization users' data as CSV.

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Ability to export the complete list of organization members to see who has access and regular audit processes.

**Are you currently working around the issue?**
Send an email to Docker support to have this .csv export.

**Comment by tehautanop** [comment]
Ability to export user data such as username and email address is in the need.

**Comment by nunocoracao** [comment]
@tehautanop sorry I made a mistake, let's use your original ticket as the main one and mark this one as a dup.

**Comment by nunocoracao** [comment]
duplicate https://github.com/docker/roadmap/issues/316

**Comment by nunocoracao** [comment]
Duplicate of https://github.com/docker/roadmap/issues/316
