### ISSUE TITLE
Tag immutability

### ISSUE THREAD

**Issue by luigilima** [docker/roadmap#416]
**Tell us about your order**
A clear and concise description of what you want to happen or the change you would like to see.
Include tag immutability

**For which services is this request made?**
Let us know which product(s) you want this for?
https://hub.docker.com/

** Tell us about the problem you are trying to solve. What are you trying to do and why is it difficult?**
Current docker hub repositories are not able to enforce tag immutability

**Comment by marcindulak** [comment]
Duplicate of https://github.com/docker/roadmap/issues/85?

**Comment by stephen-turner** [comment]
Thanks for the suggestion. Closing as dupe of #85.
