### ISSUE TITLE
[Docker Desktop for Mac] Open Docker from command line without opening window

### ISSUE THREAD

**Issue by jgresham** [docker/roadmap#419]
**Tell us about your request**
I want to be able to start Docker from the command line *without* opening a window AND without requiring the user to go into Settings to disable "Open on startup"
`open --hide --background -a Docker` 

It is explained in this StackOverflow well https://stackoverflow.com/questions/64533789/how-to-start-docker-desktop-with-a-cli-command-on-macos-without-showing-dashboar

`open --help` for more details of the open command

**Which service(s) is this request for?**
Docker Desktop for Mac, Windows, and Linux if possible!

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
My app relies on Docker running. I am trying to ensure that Docker is running in the background without requiring the user to think about running Docker AND without the user getting interrupted by the Docker window opening at all, and definitely not opening to the foreground. 

**Are you currently working around the issue?**
We ask the user to go to Settings -> disabled Open on Startup

**Additional context**

**Comment by jgresham** [comment]
If I can help with implementing this in any way, please let me know

**Comment by waldenhillegass** [comment]
I just want to say I am trying to hack out a way to do this too. This would be very helpful. @jgresham did you find a way to do this in a sane way?

**Comment by jgresham** [comment]
@waldenhillegass To see the docs for the `open` command, run `man open` on your Mac. 

The following command should work, but doesn't `open -g -j -a Docker.app`

If you want to see if Docker is stopped, the command `Docker info` will return an error.

**Comment by nunocoracao** [comment]
@jgresham @waldenhillegass seems there was a solution proposed back in Feb. Closing this ticket. Feel free to add more information and I'm happy to restart the discussion.
