### ISSUE TITLE
Hide docker desktop menu icon option for MacOS

### ISSUE THREAD

**Issue by parsanoori** [docker/roadmap#420]
**Tell us about your request**
Hide docker desktop menu icon option in preferences for MacOS.

**Which service(s) is this request for?**
Docker desktop for MacOS 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Docker desktop  icon over-populating the menu bar whilst there are versions of macbooks which have a notch bar.
On the other another person using one's laptop may accidentally and/or due to unawareness stop the docker engine which is not good. 

**Are you currently working around the issue?**
There's almost no way to maintain this right now.

**Comment by captain-pool** [comment]
Facing the same problem. Bumping this up. It's frustrating to not be able to remove the icon.

**Comment by stephen-turner** [comment]
This is a dupe of #281.
