### ISSUE TITLE
Docker Desktop: Dev Environment Mercurial Support

### ISSUE THREAD

**Issue by careymcmanus** [docker/roadmap#421]
**Tell us about your request**
I have used the new developer environments feature and I quite like it however I work with mostly mercurial repositories. Currently I can only create a dev environment from a local directory but  I would like to be able to create a dev environment from a mercurial repository.

**Which service(s) is this request for?**
Docker Des

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I can't create a dev environment from a Mercurial Repository.

**Are you currently working around the issue?**
I currently create a env from a local directory

**Comment by hyu** [comment]
Hi @careymcmanus! Thanks for submitting your issue. I'm glad to hear that you're finding Developer Environments useful!

To your question, Docker is not working on Mercurial Support for Dev Environments. We're unlikely to prioritize this, though we may review this in the future if we see significant evidence that lack of support for non-GitHub repos is limiting usage.
