### ISSUE TITLE
Future of Compose format and driving community input

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#43]
**Tell us about your request**
Create a new channel to work with the community on the future of The Docker Compose format and how the Compose files fits into the wider ecosystem of Modern Application formats and manifests 

**Which service(s) is this request for?**
Compose format

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We know that developers love working with Compose. People use Compose to 'script' running a single container or to 'string together' multi container applications to test them locally as well as in a number of places in production today. We have also heard that people want to help us create new and improved paths to production for this and establish the right future for the Compose format in the full application lifecycle. We want to work in the open with the community to understand and refine where the Compose format fits in the wider set of manifests and application definition formats. 

**Are you currently working around the issue?**
There are a range of tools and people working on this problem in isolation, from Kompose to Amazons work on ECS. We would like to find a way to bring these groups together. 

**Additional context**
N/A

**Comment by decentral1se** [comment]
> https://compose-spec.io/
