### ISSUE TITLE
[Docker Desktop Windows] Installation on different drive, data like containers still stored on default drive

### ISSUE THREAD

**Issue by MarkusWillinger** [docker/roadmap#430]
Hello, I am referencing issue  [Docker Desktop] Cannot change default installation drive on Windows? #94.
It is now possible to install Docker Desktop for Windows on custom drive location using the flag "--installation-dir". Thanks so far.
But now that Docker Desktop is installed on D: drive, nevertheless big data storage (containers etc.) still stored on default C: drive.

Directory "C:\ProgramData\Docker\" has 28 GB with only 1 container (mcr.microsoft.com/windows:ltsc2019) running.

Request:
If Docker Desktop for Windows is installed on custom drive ("--installation-dir"), then ALL the data shall be located on that drive as well.

**Comment by andrei-z-albu** [comment]
Closing this as it is already tracked by #239
