### ISSUE TITLE
Suppress Subscription Agreement popup when registry.json is in place

### ISSUE THREAD

**Issue by byjrack** [docker/roadmap#437]
**Tell us about your request**
If we are forcing folks to Sign in than the popup with the Agreement that needs to be accepted sort of is unnecessary.

**Which service(s) is this request for?**
Docker Desktop 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Just extra prompts for users that can cause confusion.

**Are you currently working around the issue?**
Just education on the click through and our license status

**Comment by stephen-turner** [comment]
Thanks for the feedback, @byjrack. We do require the agreement to be accepted on each installation; however, there is an install-time flag to accept it, which avoids it needing to be accepted on first run. See
https://docs.docker.com/desktop/install/windows-install/
https://docs.docker.com/desktop/install/mac-install/
for details on how to do that.
