### ISSUE TITLE
Docker Desktop Support for Favorite/Pinned Containers

### ISSUE THREAD

**Issue by d42ohpaz** [docker/roadmap#450]
**Tell us about your request**
The ability to favorite/pin containers to the top of the container tab of Docker Desktop for quick and easy access to commonly used containers.

**Which service(s) is this request for?**
Docker for Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It feels burdensome having to scan through a long list of containers to find the ones needed to be started. Even with the ability to sort, there is a non-trivial amount of cognitive overhead involved. The search can help, but involves more steps than a favorite/pinned container would have.

**Are you currently working around the issue?**
N/A

**Additional context**
N/A

**Comment by nunocoracao** [comment]
duplicate https://github.com/docker/roadmap/issues/379

**Comment by emirozmen07** [comment]
This would be a good feature.
