### ISSUE TITLE
 I want to create a new Organization into existing Organization

### ISSUE THREAD

**Issue by mohdrashid1** [docker/roadmap#452]
My current docker plan is team and i have only 2 organization current running i cannot create 3 organization.

So, can u tell me how many orgnization do it support in docker team plan and also docker business plan for both plan

Please tell me

That’s it!

**Comment by siarheikarneichyk** [comment]
Hi mohdrashid1,

I'm trying to understand your issue better. When you say you can't create three organizations, do you mean three teams under your organization? We have a limit of 2 teams for organizations without an active subscription. There's no limit to the number of organizations you can create. Each organization has its own subscription.

It will speed up identifying the issue if you share your docker id with us.

Thank you,
Serj Karneichyk

**Comment by ajthilakan** [comment]
Closing due to lack of engagement - if this is still relevant, pls leave a comment with more details as it can help us reconsider/investigate further 🙏
