### ISSUE TITLE
Docker desktop will exit(0) docker container immediately after running.

### ISSUE THREAD

**Issue by jorisdonkers** [docker/roadmap#455]
When running a docker image it will immediately exit after running with exit code 0. In previous versions of Docker desktop this was not the case. It looks like Docker desktop used to run all docker containers with the -it flag but not anymore. I'm using Docker desktop version 4.16.3. I can't find any information about it in the release notes. Is this intended or is this a bug?

As a side note I want to add that containers that already exist do not have this problem. It only occurs when creating a new container from a docker image when clicking on run within Docker desktop.

Reverted to docker desktop version 4.13.0 and everything works as expected again.

**Comment by thaJeztah** [comment]
This looks to be a bug-report, which would be better posted in either;

- If you're running Docker Desktop on Windows: https://github.com/docker/for-win/issues
- If you're running Docker Desktop on macOS: https://github.com/docker/for-mac/issues
 
Could you open a ticket in one of those, and provide the information requested in the issue-template on those issue trackers (including steps to reproduce and/or screenshots)?

I'll close the ticket here, but feel free to continue the conversation after I closed 👍
