### ISSUE TITLE
Hub: allow access tokens for organizations

### ISSUE THREAD

**Issue by marcelstoer** [docker/roadmap#461]
**Tell us about your request**
Docker Hub organizations should be able to hand out access tokens which grant access to all org repos.

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am one of the owners of a Docker Hub organization. The org maintains a couple of public repos for open-source projects. We push images into those repos from a GitHub Actions workflow. Hence, we need an access token to authenticate against Docker Hub. However, which token to use? 

**Are you currently working around the issue?**
An (arbitrary) owner of the organization created a dedicated access token which we use to push images to an org repo.

**Additional context**
n/a

**Comment by derKrischan** [comment]
Our org is also in need for tokens in scope of the organization. At the moment we're using personal access tokens as a work around. Nevertheless, this alway leaves the risk that if a member leaves the organization who's PAT was used for eg a pipeline, out of a sudden the pipeline stops working.

I suggest that owners of a Docker Hub organization should be able to manage tokens for the organization.

**Comment by technicallyjosh** [comment]
Hey all, an update here from engineering. 

This is something that we know has been asked for for years. We too have this issue internally and I wanted to let you know that we are currently working on some ideas on how to best accomplish this. I can't say much currently, but I can tell you that we are actively working towards some sort of solution here. 😄 

We will keep you all posted as we progress on this.

**Comment by jHubbsy** [comment]
Question: Considering @technicallyjosh response, does this mean that any personal access tokens I have set up for my user in docker hub will be valid for any repositories that exist under an organization that I am a part of?

**Comment by technicallyjosh** [comment]
Yes that is how it works currently @jHubbsy. I can confirm however that we plan to allow for fine-grained access for these PATs in the future. More to come on that as we are working out a solid roadmap around authentication/authorization right now.

**Comment by dotjoshrc** [comment]
Hello friends, just an update here.

I'm happy to confirm that we have started planning the work on org-scoped tokens 😄 We will have more to share soon! 🎉

No timeline quite yet, but it's coming!

**Comment by dotjoshrc** [comment]
Hey all, we've just released the first iteration of this! 

https://www.docker.com/blog/introducing-organization-access-tokens/

**Comment by ivotron** [comment]
thanks for this feature! I tried it out today to work with the REST API but got this:

```
Cannot log into an organization account
```

I assume that means that these tokens cannot be used with the API, is that correct? [the documentation](https://docs.docker.com/security/for-admins/access-tokens/) mentions that "You can use an organization access token when you sign in using Docker CLI" but it doesn't say that it is the only way they work. If this is limited to the CLI, it would be good to clarify on the docs.

thank you!

**Comment by dotjoshrc** [comment]
> I assume that means that these tokens cannot be used with the API, is that correct?

Hey sorry for the delay. Yes, correct, we do not support it (yet) on the API. We will be adding more scopes in the near future that will make that type of log in make sense. We started out with just registry access for now. I can say that we'll add more scopes and abilities after we finish our work here soon on Scout and Build Cloud capabilities with OATs.

**Comment by maciejXML** [comment]
bo dla mnie potrzebny ten tryb

**Comment by asfernandes** [comment]
Is this available for Free Team Orgs?
I cannot see it.

**Comment by dotjoshrc** [comment]
> Is this available for Free Team Orgs?

No, this is not supported on free orgs. Only team and business subscriptions.

**Comment by Analistarjx** [comment]
Hi i´m learning to try docker hub. @

**Comment by fazsw** [comment]
Hi, I found the `Read public repositories` is unchecked by default when creating the OAT token using the API.
Is there any possibility to enable it? I can't find it in the documentation for enabling that.

**Comment by dotjoshrc** [comment]
> Hi, I found the `Read public repositories` is unchecked by default when creating the OAT token using the API.
> Is there any possibility to enable it? I can't find it in the documentation for enabling that.

Hey thanks for reaching out here. Looks like it was missed in the docs. You should be able to add it by adding `*/*/public` as one of your paths.
