### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by arjitkumarsingh** [docker/roadmap#476]
My username is a 8 digit random number which i dont even remember. Therefore i want to change it but i couldn't find any any settings for it. please tell me how can i change my docker hub username?

**Comment by thaJeztah** [comment]
Currently, that's not possible, but there's  ticket with more information here; https://github.com/docker/roadmap/issues/44

I'll close this ticket as a duplicate of https://github.com/docker/roadmap/issues/44
