### ISSUE TITLE
[New Product] Docker Github Action

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#5]
**Tell us about your request**
Release an official Docker Github action that reduces the friction for deploying to Hub and recommends Docker best practice

**Which service(s) is this request for?**
Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We think Github actions are pretty nifty and also want to make sure people get the best out of them when they want to make use of Docker Hub

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**

**Comment by tao12345666333** [comment]
SGTM

If using GitHub Action, does it also mean it is public and can be used by anyone, not just for docker desktop?

**Comment by justincormack** [comment]
@tao12345666333 yes it will be public for anyone to use.

**Comment by olegburov** [comment]
GitHub Action has been published to GitHub Marketplace: https://github.com/marketplace/actions/build-and-push-docker-images
