### ISSUE TITLE
"Minimize to tray on start" / "Start minimized" option for Docker Desktop

### ISSUE THREAD

**Issue by jackblackevo** [docker/roadmap#502]
**Tell us about your request**
On Windows or macOS, having an option to minimize Docker Desktop on startup would be ideal, as it would prevent it from opening a new window every time the computer is rebooted.

**Which service(s) is this request for?**
Docker Desktop for Windows & Docker Desktop for Mac

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
To avoid opening a new window every time the computer is rebooted, it would be helpful to have a "Minimize to tray on start" or "Start minimized" option.

**Are you currently working around the issue?**
Having to manually close the Docker Desktop window every time.

**Additional context**
None.

**Comment by zoliszabo** [comment]
There's a "Open Docker Dashboard at startup" option, I think you are looking for that:
![image](https://github.com/docker/roadmap/assets/9949042/bf40234d-eea6-4a12-800d-5c450dbb73e9)

**Comment by jackblackevo** [comment]
Thank you!
I missed that the option is located in Docker Desktop Dashboard -> Settings -> General.
After disabling this option, it now works as expected on macOS and Windows.

**Comment by ivo-ns** [comment]
How to minimize Docker to tray? I don't want to see in on my Taskbar.

**Comment by KairuByte** [comment]
> There's a "Open Docker Dashboard at startup" option, I think you are looking for that: ![image](https://user-images.githubusercontent.com/9949042/252597701-bf40234d-eea6-4a12-800d-5c450dbb73e9.png)

For reference to anyone coming in after the fact, this technically does stop docker desktop from opening when the PC starts up... by not starting docker desktop at all, and consequently not starting the docker engine.

This *is not* the same thing as "start docker desktop minimized."

**Comment by zoliszabo** [comment]
> > There's a "Open Docker Dashboard at startup" option, I think you are looking for that: ![image](https://user-images.githubusercontent.com/9949042/252597701-bf40234d-eea6-4a12-800d-5c450dbb73e9.png)
> 
> For reference to anyone coming in after the fact, this technically does stop docker desktop from opening when the PC starts up... by not starting docker desktop at all, and consequently not starting the docker engine.
> 
> This _is not_ the same thing as "start docker desktop minimized."

No, it doesn't work that way. There's a separate option for starting (or not starting) Docker Desktop (thus Docker Engine too) when starting up your PC (in fact, when you log in, to be more exact):

![image](https://github.com/docker/roadmap/assets/9949042/8d46e65c-159d-4a75-90d6-f26cf98d0bbb)

**Comment by jackblackevo** [comment]
There is a bug in Docker Desktop version 4.27.0. The details can be found here: https://github.com/docker/for-win/issues/13887
