### ISSUE TITLE
docker installation

### ISSUE THREAD

**Issue by lovecodeandbitches** [docker/roadmap#506]
if its possible to make this entire process less cumbersome
B4CF95FD-DDCE-43E0-B84C-1122F1529B84/20230701161235

**Comment by ksaadDE** [comment]
#506 #499  #498

All of of these issues contain these GUIDs.

**Comment by macmirchdocker** [comment]
Closing the issue for lack of information - if this is related to a particular install please resubmit with additional details including the version and platform.
