### ISSUE TITLE
Border on the left of the Actions looks ugly on Dashboard

### ISSUE THREAD

**Issue by simasch** [docker/roadmap#542]
I can't remember with which version the border on the left side of the actions was introduced.
But IMO it looks very ugly and also is kind of confusing.

<img width="1515" alt="Screenshot 2023-09-11 at 08 42 21" src="https://github.com/docker/roadmap/assets/593352/c27b24c5-3b2e-4063-9037-83d28e0d54f3">

**Comment by nunocoracao** [comment]
Hello @simasch thanks for bringing this up. This was fixed in the latest release of Docker Desktop - 4.23
