### ISSUE TITLE
Integrating Docker scout with ACR (Azure container registry)

### ISSUE THREAD

**Issue by shivammittal89** [docker/roadmap#546]
Tell us about your request
Making Docker Scout available for images in cloud registries like ACR. 

Which service(s) is this request for?
Docker Scout

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
Currently Docker Scout works for Docker Hub, ECR and Artifactory. We want to enable users to use Scout with other cloud registries as well.

Are you currently working around the issue?

**Comment by amyb12345** [comment]
Duplicated

**Comment by amyb12345** [comment]
duplicated. Closing this one.
