### ISSUE TITLE
Docker Init - PHP Support

### ISSUE THREAD

**Issue by nunocoracao** [docker/roadmap#549]
**Tell us about your request**
Support for PHP in Docker init

**Which service(s) is this request for?**
Docker init CLI command

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want to be able to containerize PHP projects using docker init

**Are you currently working around the issue?**
Doing it manually, or using the generic template and then changing it. Using examples from the internet.

**Additional context**
n/a

**Comment by nunocoracao** [comment]
Related to https://github.com/docker/roadmap/issues/453

**Comment by mavimo** [comment]
PHP have a few framework that can be useful to bootstrap (Symfony / Laravel) and some of them already have a good template structure that is recognised in the community to start with (eg https://laradock.io/ or https://github.com/dunglas/symfony-docker), what the main "kind of project" will be bootstrapped here?
