### ISSUE TITLE
[Docker Desktop] Showing both docker images and docker containers in Docker Desktop

### ISSUE THREAD

**Issue by pavan168** [docker/roadmap#55]
**Tell us about your request**
I have been an early user of Kitematic. As much as it's nice to manage Docker containers directly from the new dashboard, it would be also good to have a section to list out and manage docker images created locally.

**Which service(s) is this request for?**
Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As of now, we can directly manage docker containers via the dashboard. Can we also have a section to show docker images created locally so we would not need to use the CLI. This way we will not need to manage containers via the UI and images via CLI.

**Are you currently working around the issue?**
Not at the moment. but I have the bandwidth to discuss and work on the issue if we could come to a conclusion.

**Additional context**
N/A

**Comment by stephen-turner** [comment]
@pavan168 Is this the same as #9 or is there something additional that you feel #9 doesn't cover?

**Comment by pavan168** [comment]
@stephen-turner issue #9 pretty much sums it up but in addition to that, we would like to see the docker prune functionality. We often don't check dangling images and unused images in our machines. It would be best to slowly bring this feature up or show the estimated total storage used by unused images.

**Comment by stephen-turner** [comment]
Thanks, @pavan168. I agree that prune would be very useful in the images UI, but it's already called out in #9, so I think that issue covers everything. So I'm going to close this one as a dupe.
