### ISSUE TITLE
Docker Init - Java Support

### ISSUE THREAD

**Issue by nunocoracao** [docker/roadmap#550]
Tell us about your request
Support for Java in Docker init

Which service(s) is this request for?
Docker init CLI command

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
I want to be able to containerize Java projects using docker init

Are you currently working around the issue?
Doing it manually, or using the generic template and then changing it. Using examples from the internet.

Additional context
n/a

**Comment by nunocoracao** [comment]
Related to https://github.com/docker/roadmap/issues/453

**Comment by Adesoji1** [comment]
This is great 😃 @nunocoracao

**Comment by OneCricketeer** [comment]
I'd recommend using Jib to build OCI images - https://github.com/GoogleContainerTools/jib

**Comment by nunocoracao** [comment]
Avaialble in Docker Desktop 4.27
