### ISSUE TITLE
[Docker Desktop] New Start tutorial in Docker Desktop

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#6]
**Tell us about your request**
Replace the old 'welcome whale' in Docker Desktop with a better starting tutorial that is a bit more informative and makes use of our native UI

**Which service(s) is this request for?**
Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The old welcome whale doesn't really teach you anything about Docker, we would like to give new users something a bit more constructive 

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**

**Comment by nebuk89** [comment]
Shipped! Let us know what you think and if you want more tutorials please add comments here: https://github.com/docker/roadmap/issues/62

**Comment by MestreLion** [comment]
I loved the new Tutorial, but if the Docker team is gearing towards the Docker Desktop, there should be Docker Desktop for Linux as well. It's really, really sad not to be able to follow your [101-tutorial](https://www.docker.com/101-tutorial) in a Linux environment, specially considering Docker's inheritance. Please show some love to #39 and some respect to your starting platform.
