### ISSUE TITLE
[Docker Desktop] Anytime feedback button 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#60]
**Tell us about your request**
Allow users to click an integrated feedback button in Docker Desktop to bring up a Feedback window and submit text information back to the desktop engineering team

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to achieve**
An NPS popup is not always the right way to get feedback, sometimes people want to provide feedback as they hit a problem or try out a new feature. Today this requires a user exiting desktop and raising a ticket on Github. This isn't ideal as most of our tickets are bugs or issues so this sort of feedback risks getting lost 

**Are you currently working around the issue?**
N/A

**Additional context**
N/A

**Comment by thaJeztah** [comment]
@christophermclellan as there's "feedback" buttons in various parts of the dashboard; should this one be moved to "shipped" and closed?

<img width="1083" alt="Screenshot 2022-09-20 at 16 32 19" src="https://user-images.githubusercontent.com/1804568/191286327-b4b2c2b6-f3e6-43cb-a255-270ffbc65d82.png">

<img width="1037" alt="Screenshot 2022-09-20 at 16 32 27" src="https://user-images.githubusercontent.com/1804568/191286343-69b741da-5433-41be-88c2-342c78bcf164.png">

<img width="1014" alt="Screenshot 2022-09-20 at 16 32 38" src="https://user-images.githubusercontent.com/1804568/191286346-90b4ab10-efd1-4723-a6df-0720333f815a.png">

**Comment by stephanierifai** [comment]
We're partway there with these buttons! We don't quite have the feedback form integrated into the product, but I think we can close this and open a new one when we start working on that piece.
