### ISSUE TITLE
Please provide ability to disable Docker Scout Completely on Docker Desktop

### ISSUE THREAD

**Issue by ackava** [docker/roadmap#606]
On dev machines, building new image has become extremely slow due to Docker Scout utilizing full CPU, I totally understand the purpose of Docker Scout, but there should be some way to turn it off completely while developing and testing new containers. Current workaround is to use remote Linux VM instead of Docker Desktop on our own machine to build new images.

**Comment by jonnyrobots** [comment]
In Docker Desktop, Settings > General settings > deselect `SBOM indexing`
<img width="630" alt="image" src="https://github.com/docker/roadmap/assets/13132227/a6e271d7-8c9e-4b82-92ec-a83429c51a3a">

**Comment by ackava** [comment]
Thank you.

**Comment by GorlikItsMe** [comment]
After disabling SBOM Ram and CPU usage drastically decresed. Before everything 100% usage and 10 or more docker-scout processes running in background burning my laptop. 

Maybe small note about relation between SBOM otpion in settings and docker-scout process would be helpful 🤔
