### ISSUE TITLE
docker init with golang and empty go.sum

### ISSUE THREAD

**Issue by s0rbus** [docker/roadmap#611]
I have been trying out the (relatively) new docker init command with a simple golang project. It is so simple (a web server), that it does not require any packages and so a go.sum file is not created. When I run `docker compose up --build`, I get an error because the generated Dockerfile tries to bind mount go.sum. It works if I manually create a go.sum (`touch go.sum`).

Would it be possible for the Dockerfile to check for go.sum not being available and so not try and mount it? Or create an empty go.sum file during docker init?

At the very least a warning to user before they attempt a compose build?

**Comment by nunocoracao** [comment]
Hello @s0rbus thanks for raising this. The team will look into it.

**Comment by nunocoracao** [comment]
Hello @s0rbus, this issue is fixed and it is available on the latest (4.32) release of Docker Desktop. Again thanks for raising the ticket, me and the team highly appreciate the help.
