### ISSUE TITLE
Older versions of Docker Desktop for Windows

### ISSUE THREAD

**Issue by rodrigo8763** [docker/roadmap#614]
Hi,

I can't find where I can download Docker Desktop version v3.6.0 for Windows. I read it should be in the Release Notes pages (https://docs.docker.com/desktop/previous-versions/3.x-windows/#docker-desktop-360) but I can't find it there. 

We especially need the version that can run on Windows 10 version 1809.

Thank you

**Comment by thaJeztah** [comment]
You may be able to find download-links in Git history of the documentation repository; https://github.com/docker/docs/blob/c4373d5a5f587804903297f213325dc0e9ba322f/desktop/windows/release-notes.md

But note that those versions are long obsolete, not supported, and will contain unpatched security issues.


We don't plan to add links to such versions, so I'll close this ticket, but I hope the above helps you and feel free to continue the conversation.
