### ISSUE TITLE
Dockerhub when asked for Debian, puts Ubuntu in the top result

### ISSUE THREAD

**Issue by grepwood** [docker/roadmap#619]
![obraz](https://github.com/docker/roadmap/assets/4225739/7ddda083-388e-4c3f-8a59-2cc4b6e44a10)

This is a pretty obvious bug in the way the search engine works on Dockerhub. Please fix this. The search engine was asked to find x, and instead served for "y based on x" instead of x.

**Comment by thaJeztah** [comment]
Related / similar ticket in "hub-feedback"; also looks like results-order is randomised;

- https://github.com/docker/hub-feedback/issues/2352

**Comment by benja-M-1** [comment]
Last week we released a fix for this bug. It shouldn't be the case anymore.

**Comment by grepwood** [comment]
I confirm, it's correct now. Thank you :)
![obraz](https://github.com/docker/roadmap/assets/4225739/221facc8-9623-4a45-854a-8785a04c4ac8)
