### ISSUE TITLE
[Docker Desktop] Add more tutorials 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#62]
**Tell us about your request**
Add more examples/tutorial flows into the desktop UI to help people get started with more advanced users flows from getting your own code running in a first container through to advanced best practice topics

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to achieve**
We have heard that getting started with Docker isn't easy, to help with this we are adding a simple getting started tutorial but this will only take users so far. It would be good to have a range of learning topics available to help people get started either in the UI or guides that help users in the CLI

**Are you currently working around the issue?**
N/A

**Additional context**
N/A"

**Comment by edge-ignacio-rojas** [comment]
How to build a local registry.

**Comment by jfarraraains** [comment]
Uhm... a hint of hopeful target release on edge versions would be awesome.

**Comment by hassanfarid** [comment]
I think, it should be built as importable plugins.

The tutorial content should be a importable as plugin. Docker Desktop may come as standard docker intro tutorial built in. However, community should be able to create such tutorials as well.

This way, the community and engineering teams can create product on-boarding exercises and tutorial for any internal and open source projects.

**Comment by stlucek** [comment]
Interesting idea @hassanfarid  !

**Comment by thebalaa** [comment]
We’d like to bundle Docker for Desktop with a AppStore (Mac and Windows) application. Which leads the question, is it an acceptable use of Docker for Desktop to deliver a commercial application that targets Docker for Desktop as its deployment target. 

Thanks for the feedback. Happy to discuss offline.

**Comment by stephen-turner** [comment]
@hassanfarid The current tutorial is just a container that we pull and run, so there's nothing to stop anyone creating one. The more difficult question is around discoverability.

**Comment by StefanScherer** [comment]
Hm, maybe a dashboard for https://github.com/docker/labs ?

**Comment by hassanfarid** [comment]
@stephen-turner - it will be great to have it officially supported as marketplace for docker based tuturoials.

Like you said, it is run as a container for now. Can we define, how other can build containers for the same?

For discoverability, we can leave it to community to advertise their tutorials in the documentation. For Docker Desktop perspective, we can provide cli command, `docker tutorial load <git-url>`. Essentially, by defining a template git project, that can be loaded into Docker Desktop.

Some other command maybe helpful as well like,
- `docker tutorial list`
- `docker tutorial load <git-url>`
- `docker tutorial rm <name>`

**Comment by nunocoracao** [comment]
Hello everyone, we launching a new set of walkthroughs to replace the original tutorial in the next release. We do plan to extend that set in the coming months.
