### ISSUE TITLE
Image Deprecation

### ISSUE THREAD

**Issue by sheltongraves** [docker/roadmap#622]
**Tell us about your request**
I would like to know whether an image has been deprecated whether I am looking at images on Docker Hub or within the CLI. 

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As a developer, I only want to bring maintained images into my ecosystem and want to be notified when this is not the case.

**Are you currently working around the issue?**
I have to look at the image Readme within Docker Hub to see if the image is deprecated. 

**Additional context**
N/A

**Comment by thaJeztah** [comment]
@sheltongraves I think this may be a duplicate of;

- https://github.com/docker/roadmap/issues/317
- (partially); https://github.com/docker/roadmap/issues/503

**Comment by sheltongraves** [comment]
@thaJeztah Thanks! I am going to close this issue since we have a duplicate with #317
