### ISSUE TITLE
Question: How to run docker engine from power shell if I am using Docker Desktop

### ISSUE THREAD

**Issue by saadsaeed01** [docker/roadmap#636]
**Requirement**
I have quit Docker Desktop. I want to start the Docker Engine again but through power shell. Is there any command available for starting docker engine if it is already installed?

**Current Scenario**
I can only start Docker Desktop by clicking on the Docker Desktop icon or by running the Docker Desktop exe from the command line

![image](https://github.com/docker/roadmap/assets/33133831/b8065192-48fb-435f-8c41-8d743670f249)

**Comment by Raman5677** [comment]
You can try running a script which upon clicking should initiate the Docker application.

**Comment by thaJeztah** [comment]
I don't think there's currently an official way to control Docker Desktop from the command-line, but you can execute the `Docker Desktop.exe` binary (also see https://superuser.com/questions/1498570/how-do-i-start-docker-desktop-for-windows-from-command-line)


There's an existing feature request for controlling docker desktop from the command line; you can upvote that ticket by adding a 👍 to the first comment;

- https://github.com/docker/roadmap/issues/172


I'll close this ticket as a duplicate of the above.
