### ISSUE TITLE
[Docker Desktop] Improved sign in and account creation 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#64]
**Tell us about your request**
Move to an integrated electron based sign in Window with an integrated ability to create a Docker account from within the Desktop to avoid breaking flow and reduce the number of steps to less than <5 to go from nothing to working on desktop with an account. 

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to achieve**
Today the login in desktop is basic and signup requires you to go via Docker Hubs website - this is a multi step flow that can be interrupting when are you are trying to get started. It requires a number of clicks and steps that should be collapsed. 

**Are you currently working around the issue?**
N/A

**Additional context**
N/A

**Comment by sirlatrom** [comment]
While for some, the current flow breaks the sense of immersion, it allows for users to leverage password managers either native to their browser or installed as extensions/add-ons. Make sure to leave a way out for users in that situation.

**Comment by ingshtrom** [comment]
@sirlatrom Is it not enough to use a "copy password" function of your password manager? I have to do that and it's not that bad of an experience, especially since your session might be around a month long.

**Comment by sirlatrom** [comment]
@ingshtrom It might be, except if you just downloaded Docker Desktop, you may be signed into Huh and then it's more convenient to accept the sign in in the existing session in whatever browser you were just using.

Next comes the matter of e.g. U2F or WebAuthn and whether the in-app browser supports that.
