### ISSUE TITLE
Your REPO have been down for some time

### ISSUE THREAD

**Issue by spirillen** [docker/roadmap#647]
When I try to update via `deb.nodesource.com` I get access denied

```bash
Err:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.12.2-1nodesource1
403  Forbidden [IP: 104.22.4.26 443]
E: Failed to fetch https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.12.2-1nodesource1_amd64.deb  403  Forbidden [IP: 104.22.4.26 443]

Err:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.12.2-1nodesource1
403  Forbidden [IP: 104.22.4.26 443]
E: Failed to fetch https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.12.2-1nodesource1_amd64.deb  403  Forbidden [IP: 104.22.4.26 443]
```

Maybe you have a right to privacy issue? banning all tor without proper reasons?

**Comment by macmirchdocker** [comment]
Hello @spirillen - could you please provide further information on what you are trying to accomplish and within which environment configurations so we could better assess.  Thank you!

**Comment by spirillen** [comment]
> which environment

Doesn't matter

As any other people, I do blacklist the MITM network Cloudflare, which forces me to use the tor network to try to update my nodes from your repo's, but you are blacklisting all privacy aware networks that tried to access your repo

**Comment by macmirchdocker** [comment]
This appears related to Nodesource setup which is not maintained or owned by Docker. The error message copied is not related to errors generated by Docker systems.  As such I am going to close the issue - but please reopen if you have further input.
