### ISSUE TITLE
[Docker Desktop] Release Docker Template

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#65]
**Tell us about your request**
Release Docker Template as part of Docker Desktop Community. Docker template allows you to create new containerized applications from example 'templates' stored in Docker hub. To learn more : https://www.docker.com/blog/application-templates-docker-desktop-enterprise/

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Getting started with Docker can be tough, especially when you are trying to build a new multi container application. Finding an example and getting it built locally with the framework versions you want to use isn't always easy and there are a lot of sources to choose from.

**Are you currently working around the issue?**
N/A

**Additional context**
N/A

**Comment by xinity** [comment]
related to the opensource release of this AppDesigner.
Definitely would be great to have both 👍
