### ISSUE TITLE
Support Ubuntu 24.04 for Docker Desktop

### ISSUE THREAD

**Issue by vacla** [docker/roadmap#655]
Tell us about your request?
Docker desktop official support for ubuntu 24.04

Which service(s) is this request for?
docker desktop/docker cli

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
there is no official support and docker desktop straight up doesn't open, need it for work.

Are you currently working around the issue?
no

**Comment by kiabo** [comment]
I experience this problem too and there is an open forum for this with several people participating. It would be very interesting if you no longer needed a hack to access docker-desktop on Ubuntu 24. 

This is the forum: 
[https://forums.docker.com/t/cannot-get-docker-desktop-to-run-on-ubuntu-24-04/141004](https://forums.docker.com/t/cannot-get-docker-desktop-to-run-on-ubuntu-24-04/141004)

**Comment by thaJeztah** [comment]
Thanks for your ticket.

We started publishing `deb` packages for docker-ce ("docker engine") and the docker cli for Ubuntu 24.04 on download.docker.com, but I'm not sure what the current status is for docker desktop (and if it has been fully verified for the Ubuntu 24.04 release).

I'm not on the team maintaining Docker Desktop for Linux, so let me ask that team if they have more information (and to have a look at the issues reported on the forum).

**Comment by wgrs** [comment]
I tried to run 4.28.0 - it wont start.

I then removed docker completely and installed 4.29.0. This ran as expected yesterday. Today ( after a reboot) its not starting either.

**Comment by ndraiman** [comment]
There's a workaround, but it exposes a security issue, you can read more here: https://github.com/docker/desktop-linux/issues/209

**Comment by wgrs** [comment]
> Thanks for your ticket.
> 
> We started publishing `deb` packages for docker-ce ("docker engine") and the docker cli for Ubuntu 24.04 on download.docker.com, but I'm not sure what the current status is for docker desktop (and if it has been fully verified for the Ubuntu 24.04 release).
> 
> I'm not on the team maintaining Docker Desktop for Linux, so let me ask that team if they have more information (and to have a look at the issues reported on the forum).

Did you ask them for more information?

**Comment by thaJeztah** [comment]
> Did you ask them for more information?

Yes, I asked; team was aware of this, and had a couple of pull-requests related to this, but it was a non-trivial change to make (various parts affected that needed a rewrite); it's still being worked on, but I don't have an ETA currently.

**Comment by mloskot** [comment]
@thaJeztah 
> We started publishing deb packages for docker-ce ("docker engine") and the docker cli for Ubuntu 24.04

Yes, and the official documentation is also available at https://docs.docker.com/engine/install/ubuntu/ but there seem to be problems at step 2. of the [Install using the apt repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository):

```bash
$ sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'moby-containerd' instead of 'containerd.io'
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  moby-cli:armhf moby-engine:armhf moby-cli:arm64 moby-engine:arm64 moby-engine moby-cli

Package docker-ce-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  moby-cli:armhf moby-cli:arm64 moby-cli

Package docker-buildx-plugin is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  moby-buildx:armhf moby-buildx:arm64 moby-buildx

E: Package 'docker-ce' has no installation candidate
E: Package 'docker-ce-cli' has no installation candidate
E: Package 'docker-buildx-plugin' has no installation candidate
E: Unable to locate package docker-compose-plugin
```

**Comment by thaJeztah** [comment]
@mloskot That error seems to indicate that either the apt-repository is not properly setup; the content of `/etc/apt/sources.list.d/docker.list` should look something like;

```bash
cat /etc/apt/sources.list.d/docker.list
deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable
```

(the `arch=` bit depending on the hardware architecture you're running on)

In addition, based on some of the messages, I suspect this may be on a machine that's connected to Microsoft's package repositories and has docker setup from their packages. Microsoft packages `docker-ce` as `moby-engine` in their package repositories, and it looks like those packages have a `Replace` directive, which means they "shadow" the `docker-ce` packages;

```
Note, selecting 'moby-containerd' instead of 'containerd.io'
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  moby-cli:armhf moby-engine:armhf moby-cli:arm64 moby-engine:arm64 moby-engine moby-cli
```

The installation instructions already have a step to uninstall packages that are known to conflict (for situations where docker is to be installed on an existing machine that may already have some other distributions of docker installed), but it looks like it currently does not take those packages into account, as they're less common (i.e., not part of packages provided by the Linux distribution itself); https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions

<img width="936" alt="Screenshot 2024-09-25 at 11 21 15" src="https://github.com/user-attachments/assets/93552101-a7f2-4321-84cf-2adf1fd0b7fb">

**Comment by mloskot** [comment]
@thaJeztah I have followed the guide step by step, including the uninstallation part. However, I made a mistake by dumbly copying these commands from the step 1. and pasting into terminal

![image](https://github.com/user-attachments/assets/c80a80d0-728e-4192-b18b-79d2eaed38db)

making a mistake by not noticing there is no `&& \` continuation at the end of the `sudo` commands.

Pasting and executing those commands one by one deployed the correct `/etc/apt/sources.list.d/docker.list` indeed, and that obviously did the trick. Thank you and apologies for the unnecessary noise.

**Comment by thaJeztah** [comment]
No worries! Let me hide those last few comments as "off-topic" to keep the discussion more on topic 👍

**Comment by sswartzl** [comment]
Has there been an ETA established for this?

**Comment by KatTomrushka** [comment]
Thank you for your interest and patience. We want to let you know that we’re actively working on the Linux Ubuntu 24.04, and it's already in the testing phase. It’s coming soon, though we don’t have a confirmed release date just yet.

We’ll keep you updated as progress continues!

**Comment by kavinduWimalasooriya** [comment]
I also have this problem with Ubuntu 24.04. I clicked the Docker Desktop icon, but nothing happens. However, when I checked the status of the Docker Desktop service, it shows as running.

**Comment by KatTomrushka** [comment]
Hi friends, Ubuntu 24.04 is now supported on Docker Desktop as of v.4.35 

https://docs.docker.com/desktop/release-notes/

**Comment by Ignacio-Trottaa** [comment]
Docker Desktop does not open on Ubuntu 22.04 Noble, I have the latest version.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

**Comment by KatTomrushka** [comment]
> Docker Desktop does not open on Ubuntu 22.04 Noble, I have the latest version. Distributor ID: Ubuntu Description: Ubuntu 24.04.1 LTS Release: 24.04 Codename: noble

Hey @Ignacio-Trottaa Sorry to hear about this! Can you please help us investigate what's going on by passing us the diagnostic id following instructions in https://docs.docker.com/desktop/troubleshoot/#diagnose-from-the-terminal? Thank you!
