### ISSUE TITLE
[Docker Desktop] Archive Kitematic 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#67]
**Tell us about your request**
We will aim to archive the Kitematic project once we have feature parity in the Docker Desktop UI, this will give us more time to focus on a single UI for containers on the desktop. 

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to achieve**
Today we have two UI's for users of Desktop - the built in UI and Kitematic. 

**Are you currently working around the issue?**
N/A

**Additional context**
N/A

**Comment by mat007** [comment]
https://github.com/docker/kitematic has now been deprecated and archived.

**Comment by SalahAdDin** [comment]
Hi, 

We linux users, what can we use instead of kitematic?

**Comment by Cediddi** [comment]
> Hi,
> 
> We linux users, what can we use instead of kitematic?

Dockstation is a good alternative, It has AppImage and deb package but you can find it on many platforms as well.

**Comment by SalahAdDin** [comment]
> > Hi,
> > We linux users, what can we use instead of kitematic?
> 
> Dockstation is a good alternative, It has AppImage and deb package but you can find it on many platforms as well.

Is it more outdated than **Kitematic**.

**Comment by chainslunatic** [comment]
> Hi,
> 
> We linux users, what can we use instead of kitematic?

By now you can use [Docker Desktop for Linux](https://docs.docker.com/desktop/linux/install/)

**Comment by stephanierifai** [comment]
Thanks @chainslunatic. Closing this! A related ticket that might be worth following:

- https://github.com/docker/roadmap/issues/75
