### ISSUE TITLE
Docker desktop gets auto-updated despite disabling auto-update.

### ISSUE THREAD

**Issue by PawelMaslak** [docker/roadmap#672]
**Tell us about your request**
I need to use slightly older version of Docker 4.25.0 as I am provided docker compose file by my organization which I do not want to edit to remove all obsolete code. Given this I want to use 4.25.0 without being surprised every two days with latest version automatically installed. 

My settings is always set to this:
![settings](https://github.com/docker/roadmap/assets/44748177/61576eab-5ec7-42e4-a47c-38c4aeec25f5)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Whenever I install the docker I disable auto-updates. Sometimes it lasts for a day, sometimes for a week but eventually docker gets annoyingly auto-updated. I tried solutions from other issues users posted here but nothing worked such as: 

`Get-BitsTransfer | Remove-BitsTransfer` to remove pending downloads of the update.

Docker at some point restarts and informs me that new version has been installed:

![Docker](https://github.com/docker/roadmap/assets/44748177/e8895f50-f232-4f2f-bea0-b605ff405507)

The failed item refers to docker compose for which some of the commands are obsolete:
![Powershell](https://github.com/docker/roadmap/assets/44748177/fd6aac2e-3b0e-45cc-8419-6004bbc3d70d)

**Are you currently working around the issue?**
I always need to reinstall Docker to older version such as 4.25.0, pull my images and create containers.

I downgraded today to 4.24.0 and we will se how long it will last before getting auto-update:
![docker-update](https://github.com/docker/roadmap/assets/44748177/c97376ef-5354-44c7-9eac-ae568b14bb85)

Update:
Version 4.24.0 worked literally for few hours before being again auto updated:
![updated - again](https://github.com/docker/roadmap/assets/44748177/9b3f556c-cb2b-4e2c-8e36-871c8a153410)
![docker-service](https://github.com/docker/roadmap/assets/44748177/c6fd54eb-c765-49d3-8d14-29747f0d5261)

**Comment by KatTomrushka** [comment]
Thank you for submitting this. The issue you report is in an older DD version - we recommend you update to the latest DD version instead.

**Comment by Chronicle20** [comment]
This is still an issue, even in Docker Desktop 4.42.0. Just got auto-updated to 4.42.1 with both settings disabled.
