### ISSUE TITLE
[Docker Desktop] Image vulnerability scanning on Desktop 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#69]
**Tell us about your request**
Scan images for vulnerabilities to ensure they are checked against an aggregated set of Common Vulnerabilities and Exposures (CVEs).

**Which service(s) is this request for?**
Docker Desktop 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Desktop told us they care about security and running things locally means using your own compute making it cheaper when doing smaller or personal projects. To support this we could add scanning in desktop to support:

- Scan container images for Common Vulnerabilities and Exposures (CVEs)
- List by severity the software vulnerabilities that were discovered, based on the Common Vulnerabilities and Exposures (CVEs) database

**Are you currently working around this issue?**
N/A

**Additional context**
N/A

**Attachments**
N/A

**Comment by xinity** [comment]
while i'd really like to see this feature built-in into Docker Desktop , i'm not really sure about ressource consumption of that feature.

solution like trivy from aquasec could be interesting to add as an opt-in feature.
depending on this integration this could also lead to higher disk usage.
Might worth a try in an edge release , but yes definitely worth the feature 👍

**Comment by ingshtrom** [comment]
Alternatively, while this doesn't "use your own compute", Desktop could dish out to Hub as well to perform the scanning. ref: https://github.com/docker/roadmap/issues/18

**Comment by nebuk89** [comment]
Dupe of https://github.com/docker/roadmap/issues/95 - closing :)
