### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Julytampos** [docker/roadmap#697]
**Tell us about your request**
A clear and concise description of what you want to happen or the change you would like to see

**Which service(s) is this request for?**
Let us know which product(s) you want this for?

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

**Are you currently working around the issue?**
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/docker/roadmap/issues/696
```

**Comment by Julytampos** [comment]
{
  "user-data-v2": {
    "activeUser": {
      "uuid": "0de73b82-67b1-41fa-ac72-d1fe5daa828c",
      "username": "Account 1",
      "hasMnemonic": true
    },
    "users": [
      {
        "uuid": "0de73b82-67b1-41fa-ac72-d1fe5daa828c",
        "username": "Account 1",
        "hasMnemonic": true
      }
    ]
  },
  "keyring-store-v2": "REMOVED",
  "migration-log": [
    {
      "build": 10661979,
      "state": "finalized"
    }
  ],
  "unlocked-until": "1722277873098",
  "wallet-data_0de73b82-67b1-41fa-ac72-d1fe5daa828c": {
    "autoLockSettings": {
      "seconds": 600
    },
    "approvedOrigins": [
      "https://app.hawahash.xyz"
    ],
    "developerMode": false,
    "aggregateWallets": false,
    "networkConfigs": {},
    "preferencesLastUpdated": 1722278865413
  },
  "public-key-store-v2": {
    "0de73b82-67b1-41fa-ac72-d1fe5daa828c": {
      "activePlatform": "ethereum",
      "platforms": {
        "ethereum": {
          "activePublicKey": "0x8Df1c9A97b5DCFB73c357C525d67E532ed4e749d",
          "blockchain": "ethereum",
          "publicKeys": {
            "0x8Df1c9A97b5DCFB73c357C525d67E532ed4e749d": {
              "name": "Wallet 1",
              "type": "derived",
              "walletType": "evm-default"
            }
          }
        }
      }
    }
  },
  "last-migration": {
    "build": 10661979,
    "state": "finalized"
  },
  "randomness-keyring-v2": "28",
  "mobile-store-migrated": "true"
}

**Comment by savannahostrowski** [comment]
Closing this as this issue just wraps #696
