### ISSUE TITLE
Kubernetes CLI tooling in WLS Ubuntu 

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/roadmap#72]
**Tell us about your request**
Linux and Windows toolset for Kubernetes
**Which service(s) is this request for?**
Kubernetes tooling:
"normal" kubctl, Helm, etc.

**Docker Desktop has the option to run Kuberenetes orchestration but no tools are provided. Also, most examples can run neither in Windows CMD nor Powershell [...]

**Are you currently related to Kubernetes CLIs  working around the issue?**
I solved via 1. Installing Kubernetes client in my WSL Ubuntu using apt-get 2. creating the symbolic link between kubeconfig in Linux and Windows to avoid double maintenance, 3. installing Helm 3.1 ( exists now both for Windows and Linux!) 
Ansible beta also runs in WSL Ubuntu
Of course, VS Code with Microsoft development containers is installed on my computer.
**Additional context**
I prefer to have and maintain consistently a single powerful computer for full-stack application development with a convenient combination of tools for local and cloud development instead of a random collection of hardware and software. It can be a convenient toolbox for students for only 600$

**Comment by nebuk89** [comment]
Is this an ask for WSL or WSL 2? In WSL 2 we bundle and setup K8s for use with your distro so you should be able to use kubctl

**Comment by thaJeztah** [comment]
From the conversation above, it looks like this is  addressed by Docker Desktop for Windows with WSL2 enabled, which comes with the kubernetes tooling, so let me close this ticket.
