### ISSUE TITLE
[Docker Hub] Repo Insights

### ISSUE THREAD

**Issue by pkennedyr** [docker/roadmap#74]
**Tell us about your request**
Provide metrics and analytical reports to help developers and teams understand and improve how their images are being built and consumed via Docker Hub (e.g. checklist of Dockerfile best practices, pull activity per tag, geo distribution of where content is pulled).

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
There is currently no easy way to to get insight into the activity of a team when building images on Docker Hub nor how images are being consumed by the Hub community. Docker Hub customers often cite a desire to visualize their current team activity, get up-to-date reports on pull activity, and understand how the Hub community is consuming their images on Docker Hub.

**Are you currently working around the issue?**
NA

**Additional context**
NA

**Comment by christophermclellan** [comment]
Good point, thanks @ingshtrom !

**Comment by amyb12345** [comment]
@pkennedyr Does our solution of [Insights and Analytics](https://docs.docker.com/docker-hub/publish/insights-analytics/) solve your problem? It's only available to our Trusted Content Programs, but we'd be interested in learning more if participating in one of those programs isn't applicable to your use case.  

To be clearer, is your request for the analytics on our repos to help understand how those outside your team are using the images or is it specifically for devs within your team or org?
