### ISSUE TITLE
Bundle Docker for Desktop with a Mac / Windows App

### ISSUE THREAD

**Issue by thebalaa** [docker/roadmap#77]
I'd like to bundle Docker for Desktop with an AppStore (Mac and Windows) application. Which leads the question: Is delivering a commercial application that uses Docker for Desktop as its deployment target an acceptable use case for Docker for Desktop?

Thanks for the feedback!

**Comment by nebuk89** [comment]
Hey @thebalaa drop me an email on ben.destpaer-gotch@docker.com to chat about this further!

Thanks

**Comment by thebalaa** [comment]
Sent you an email @nebuk89, never heard back.
