### ISSUE TITLE
[Docker Desktop] Release MSI installer

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#8]
**Tell us about your request**
Provide an MSI installer for Community Desktop to make it easier for managed deployments of free Docker Desktop

**Which service(s) is this request for?**
Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Managed deployments with an .exe are harder than with an MSI and this will ease the burden for those in an enterprise setting

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**

**Comment by nebuk89** [comment]
Having investigated the cost of this and looking at this compared to other things we could work on  such as
https://github.com/docker/roadmap/issues/12 
and 
https://github.com/docker/roadmap/issues/7 
- we won't be doing this in the near term. Moving back out of investigation.

**Comment by EnigmaV8** [comment]
Not having an MSI for the Community edition is VERY disappointing news!  And how is there a high cost to develop this?!  You already have one for the more complex Enterprise Edition.

**Comment by KatTomrushka** [comment]
Hi everyone! We are reviewing this topic for 2024 and would love to hear your feedback, in terms of operational context, how MSI helps and any other thoughts on how to improve Docker Desktop installation and package deployments. 

Feel free to book some time with me: https://calendly.com/kat-tomrushka/30min

**Comment by sean-finley-eptura** [comment]
Trying to deploy the Leaky Vessels fix in an enterprise would be so much easier with an MSI.

**Comment by KatTomrushka** [comment]
We are pleased to announce that we have commenced development on the new installer. 
Should you have any insights or suggestions you'd like to share, we warmly invite you to leave a comment here, utilize the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSfSuknJ33HclT17ppxo2-Q1OU2LX0WWOdntSjor6QttJSyaow/viewform), or [arrange a brief interview](https://calendly.com/kat-tomrushka/30min) with me. Your input is invaluable to us, and we look forward to hearing your thoughts. Thank you!

**Comment by KatTomrushka** [comment]
The MSI is already shipped and available for business customers! 
https://www.docker.com/blog/docker-desktop-msi-installer-login-enforcement-alternatives
