### ISSUE TITLE
[Open source] Docker Update For Ubuntu 20.04

### ISSUE THREAD

**Issue by abhaykeerthy12** [docker/roadmap#83]
**Tell us about your request?** 
Docker official support for ubuntu 20.04

**Which service(s) is this request for?** 
docker cli

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?** 
there is no official support

**Are you currently working around the issue?** 
no

**Comment by StefanScherer** [comment]
Thank you. We are already working on this internally. The next patch release is expected to have packages for Ubuntu Focal Fossa.

**Comment by nebuk89** [comment]
Moved to correct status :)

**Comment by StefanScherer** [comment]
Docker 19.03.9 is released, with packages for Ubuntu Focal Fossa.
Thanks for you patience. Enjoy!

**Comment by abhaykeerthy12** [comment]
Thanks

**Comment by justincormack** [comment]
Closing as resolved now.
