### ISSUE TITLE
[Docker Open Source] Deprecate Classic Swarm

### ISSUE THREAD

**Issue by justincormack** [docker/roadmap#86]
**Tell us about your request**
Classic Swarm https://github.com/docker/classicswarm was an early orchestration system we introduced in 2014. It is often confused with the later Swarmkit based Swarm mode in Docker engine which is usually also called "Docker Swarm", and most of the issues on the GitHub repo are confusion about this. We have not been maintaining this actively for many years, and would like to formally deprecate it.

If you are an active user of Classic Swarm please let is know here.

**Which service(s) is this request for?**
Classic Swarm

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Introduce more clarity about which open source tools we are developing actively, focus on tools that are being used and have active communities.

**Are you currently working around the issue?**
We are not maintaining this actively, but have not made it clear what the status and roadmap is.

**Additional context**
This is nothing to do with Docker Swarm, which there are no plans to deprecate. The confusion in names is unfortunate.

**Comment by ximon18** [comment]
Given a news articles [like this](https://www.mirantis.com/blog/mirantis-acquires-docker-enterprise-platform-business/) which says _"[Mirantis] expects to support Swarm for at least two years"_ is Swarmkit based Swarm mode the thing that has a potential maximum shelf-life of two years, or Classic Swarm? Perhaps it would be better if Swarmkit is still being actively (and beyond two years) supported to rebrand it completely.

**Comment by justincormack** [comment]
Mirantis is referring to Swarmkit. They do not support Classic Swarm. Once we deprecate Classic Swarm there should only be the one Swarm, which should be less confusing!

**Comment by ximon18** [comment]
So then the situation regarding clarity around Swarm is somewhat a moot point if it potentially won't be supported anyway, as Swarm Classic is not supported and will be deprecated and Swarmkit is only supported for max 2 years depending on how much one can trust Mirantis to continue to support it, let alone invest in it?

**Comment by justincormack** [comment]
Swarm Classic and Swarmkit/Docker Swarm are totally unrelated. They share no code, or UI, they just unfortunately have the same name, as in a sense Swarm Classic was a kind of beta version of SwarmKit. So potentially deprecating Swarm Classic has no bearing at all on the future of Swarm.

**Comment by ximon18** [comment]
Perhaps I misunderstand the situation but I feel like I am not making myself clear. The announcement from Mirantis does not inspire confidence that Swarmkit will be supported > 2 years and puts Swarmkit in second place by saying "The primary orchestrator going forward is Kubernetes" and so inspires no confidence that Swarmkit will be invested in. In such a situation what does it matter whether it is clear which is Swarm Classic and which is Swarmkit given that both are on the path to obsolescence? Don't get me wrong, I like and am actively using Swarmkit and like the simplicity of setting it up and using it, and was hoping that this GitHub issue might mean that Swarmkit will be actively maintained and invested in - so please do correct me.

**Comment by justincormack** [comment]
This GitHub issue is nothing to do with SwarmKit. It is about a completely different product. If you want to talk about SwarmKit please open a new issue on this repo.

**Comment by ximon18** [comment]
Okay, thx, but then I’m even more confused than I was. I tried to get a point across but it seems that I’m not succeeding. Let’s see what the future brings.

**Comment by BretFisher** [comment]
@ximon18 SwarmKit has no end planned. "Classic" Swarm does. [Mirantis updated their announcement months back](https://www.mirantis.com/blog/mirantis-will-continue-to-support-and-develop-docker-swarm/) that they are expanding the SwarmKit team and adding new features (one has already hit moby master). 

Like @justincormack says, this GH Issue, however, is about a different product that keeps getting confused with SwarmKit and needs to be archived. The future of SwarmKit is fine, and we talk about it on my show here: https://youtu.be/L5N43aQQArw

**Comment by BretFisher** [comment]
In addition to the GitHub project itself, there are lots of docker docs that simply say "Swarm" but should now say Classic Swarm and indicate an archive/deprecation notice at the top of each page. Here's an example:

https://github.com/docker/docker.github.io/blob/master/swarm/scheduler/strategy.md

**Comment by ximon18** [comment]
Thanks @BretFisher. I understand that @justincormack is referring to a different product, but this issue IMO _only_ makes sense if SwarmKit has a future, which wasn't clear to me. I hadn't seen that [update from Mirantis](https://www.mirantis.com/blog/mirantis-will-continue-to-support-and-develop-docker-swarm/) which indeed makes it clear that SwarmKit (they don't call it SwarmKit but I understand from this discussion they mean SwarmKit and not "Classic" Swarm) has a future. and I'm very grateful to learn that and for the reference.

I'm not convinced that deprecating "Classic" Swarm will be enough to resolve the confusion about the product names, and that only a rename of Swarm/SwarmKit/Docker Swarm has the potential to help. However, I don't have a proposed alternate name, and rebranding is complex and will also cause confusion. Calling it Mirantis Swarm might help but only until Mirantis get bought out or sell it on and then it will just be even more confusing...

**Comment by justincormack** [comment]
@BretFisher we moved the docs out of the main repo to the classic swarm repo, which will hopefully avoid this. If you spot any other references please let me know.

**Comment by justincormack** [comment]
The repo has now been archived.
