### ISSUE TITLE
[Docker Desktop] Desktop Images UI

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#9]
**Tell us about your request**
Provide a UI with Visibility into Hub and local images in Docker Desktop, with the ability to manage local images (prune, update etc)

**Which service(s) is this request for?**
Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have had feedback that this would be useful to understand what images people have locally, what versions, when they were last updated and to manage the removal of unused images

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**

**Comment by psychemedia** [comment]
In the initial desktop release of images, the container launch panel supports port and mount setting.

![](https://lh4.googleusercontent.com/U04KCx5ODC1kuAvkTuMbjUfMFiHqPaXU87_6ZicGZuHZcsosWsorYWjZWcLY7iyt73mse4T8Pve_Ed9XpnNfPnTd1Ri65qByr4_xJixE432dekVqenf0jUIHtRlQIgbTsjMieItg)

It would also be used to allow the user to enter one or more environment variable name-vale pairs, replicating the `docker run -e` flag.

**Comment by nebuk89** [comment]
@psychemedia thank you for the feedback! I am going to mark this ticket as closed for the initial ship but we do have plans to add some more items including env and command for starting the container :)
