### ISSUE TITLE
[Docker Desktop] Image Vulnerability Scanning in the Docker CLI (w/Snyk!)

### ISSUE THREAD

**Issue by 412PIT** [docker/roadmap#95]
*Tell us about your request*
In partnership with Snyk, scan images for vulnerabilities to ensure they are checked against an aggregated set of Common Vulnerabilities and Exposures (CVEs).

Which service(s) is this request for?
Docker Desktop, in partnership with Snyk

*Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?*
Developers have cited the desire to easily view and manage image vulnerabilities from within Docker Desktop, including (but not limited to):

- Scan container images for Common Vulnerabilities and Exposures (CVEs)
- Configure a repo to scan images on push to a repository
- Configure a repo to manually scan container images within a repository
- List by severity the software vulnerabilities that were discovered, based on the Common Vulnerabilities and Exposures (CVEs) database
- Provide guidance on how to remediate a discovered vulnerability in an image
- Rescan existing images
- Vulnerability scanning during local development

Are you currently working around this issue?
N/A

Additional context
N/A

Attachments
N/A

**Comment by esemate** [comment]
Is this feature available in Linux?

**Comment by nebuk89** [comment]
@esemate not right now but we are looking at sorting this out as a binary or as part of a package for linux. Feel free to open a fresh roadmap issue for this (as this ticket was intended to just cover Mac/Win) 
Thanks!
